In [45]:
import pandas as pd

In [48]:
data = pd.read_csv('weatherAUS.csv')

In [49]:
data.shape

(142193, 24)

In [50]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null object
RISK_MM          142193 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(17), object(7)
memory usage: 26.0+ MB

In [52]:
 data.isna().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [53]:
data[data['Cloud9am'].isna()].head

<bound method NDFrame.head of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
1       2008-12-02   Albury      7.4     25.1       0.0          NaN
2       2008-12-03   Albury     12.9     25.7       0.0          NaN
3       2008-12-04   Albury      9.2     28.0       0.0          NaN
5       2008-12-06   Albury     14.6     29.7       0.2          NaN
7       2008-12-08   Albury      7.7     26.7       0.0          NaN
8       2008-12-09   Albury      9.7     31.9       0.0          NaN
9       2008-12-10   Albury     13.1     30.1       1.4          NaN
10      2008-12-11   Albury     13.4     30.4       0.0          NaN
13      2008-12-14   Albury     12.6     21.0       3.6          NaN
17      2008-12-19   Albury     11.2     22.5      10.6          NaN
18      2008-12-20   Albury      9.8     25.6       0.0          NaN
19      2008-12-21   Albury     11.5     29.3       0.0          NaN
20      2008-12-22   Albury     17.1     33.0       0.0          NaN
21      2008-12-23   Albury     20.5     31.8       0.0          NaN
23      2008-12-25   Albury     12.6     32.4       0.0          NaN
24      2008-12-26   Albury     16.2     33.9       0.0          NaN
25      2008-12-27   Albury     16.9     33.0       0.0          NaN
26      2008-12-28   Albury     20.1     32.7       0.0          NaN
27      2008-12-29   Albury     19.7     27.2       0.0          NaN
30      2009-01-01   Albury     11.3     26.5       0.0          NaN
31      2009-01-02   Albury      9.6     23.9       0.0          NaN
32      2009-01-03   Albury     10.5     28.8       0.0          NaN
33      2009-01-04   Albury     12.3     34.6       0.0          NaN
34      2009-01-05   Albury     12.9     35.8       0.0          NaN
35      2009-01-06   Albury     13.7     37.9       0.0          NaN
36      2009-01-07   Albury     16.1     38.9       0.0          NaN
37      2009-01-08   Albury     14.0     28.3       0.0          NaN
38      2009-01-09   Albury     12.5     28.4       0.0          NaN
39      2009-01-10   Albury     17.0     30.8       0.0          NaN
40      2009-01-11   Albury     16.9     32.0       0.0          NaN
...            ...      ...      ...      ...       ...          ...
142157  2017-05-20    Uluru      4.1     26.0       0.0          NaN
142158  2017-05-21    Uluru      7.2     29.4       0.0          NaN
142159  2017-05-22    Uluru      9.7     30.0       0.0          NaN
142160  2017-05-23    Uluru      7.6     27.1       0.0          NaN
142161  2017-05-24    Uluru     10.1     26.7       0.0          NaN
142164  2017-05-27    Uluru      9.3     28.0       0.0          NaN
142168  2017-05-31    Uluru      5.4     20.5       0.0          NaN
142169  2017-06-01    Uluru      5.6     19.4       0.0          NaN
142170  2017-06-02    Uluru      1.5     19.2       0.0          NaN
142171  2017-06-03    Uluru      3.8     19.8       0.0          NaN
142172  2017-06-04    Uluru      4.5     18.8       0.0          NaN
142173  2017-06-05    Uluru      4.9     20.7       0.0          NaN
142174  2017-06-06    Uluru      1.2     20.8       0.0          NaN
142175  2017-06-07    Uluru      0.5     21.7       0.0          NaN
142176  2017-06-08    Uluru      4.0     20.0       0.0          NaN
142177  2017-06-09    Uluru      3.4     19.8       0.0          NaN
142178  2017-06-10    Uluru      3.2     18.6       0.0          NaN
142179  2017-06-11    Uluru      2.4     19.1       0.0          NaN
142180  2017-06-12    Uluru      5.1     19.7       0.0          NaN
142181  2017-06-13    Uluru      2.5     21.2       0.0          NaN
142182  2017-06-14    Uluru      2.3     21.4       0.0          NaN
142183  2017-06-15    Uluru      2.6     22.5       0.0          NaN
142184  2017-06-16    Uluru      5.2     24.3       0.0          NaN
142185  2017-06-17    Uluru      6.4     23.4       0.0          NaN
142186  2017-06-18    Uluru      8.0     20.7       0.0          NaN
142187  2017-06-19    Uluru      7.4     20.6       0.0          NaN
142188  2017-06-20    Uluru      3.5     21.8       0.0          NaN
142189  2017-06-21    Uluru      2.8     23.4       0.0          NaN
142190  2017-06-22    Uluru      3.6     25.3       0.0          NaN
142191  2017-06-23    Uluru      5.4     26.9       0.0          NaN

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  \
1            NaN         WNW           44.0        NNW  ...        25.0
2            NaN         WSW           46.0          W  ...        30.0
3            NaN          NE           24.0         SE  ...        16.0
5            NaN         WNW           56.0          W  ...        23.0
7            NaN           W           35.0        SSE  ...        19.0
8            NaN         NNW           80.0         SE  ...         9.0
9            NaN           W           28.0          S  ...        27.0
10           NaN           N           30.0        SSE  ...        22.0
13           NaN          SW           44.0          W  ...        43.0
17           NaN         SSE           43.0        WSW  ...        32.0
18           NaN         SSE           26.0         SE  ...        26.0
19           NaN           S           24.0         SE  ...        28.0
20           NaN          NE           43.0         NE  ...        28.0
21           NaN         WNW           41.0          W  ...        24.0
23           NaN           W           43.0          E  ...        17.0
24           NaN         WSW           35.0         SE  ...        19.0
25           NaN         WSW           57.0        NaN  ...        28.0
26           NaN         WNW           48.0          N  ...        15.0
27           NaN         WNW           46.0         NW  ...        22.0
30           NaN         WNW           56.0          W  ...        26.0
31           NaN           W           41.0        WSW  ...        22.0
32           NaN         SSE           26.0        SSE  ...        22.0
33           NaN         WNW           37.0        SSE  ...        12.0
34           NaN         WNW           41.0        ENE  ...         9.0
35           NaN           W           52.0         SE  ...         8.0
36           NaN           W           57.0          E  ...        12.0
37           NaN           W           48.0          W  ...        15.0
38           NaN          NE           37.0        SSE  ...        16.0
39           NaN          NE           37.0        NNE  ...        24.0
40           NaN           S           31.0        SSE  ...        31.0
...          ...         ...            ...        ...  ...         ...
142157       NaN          NW           26.0         SE  ...        22.0
142158       NaN         NNW           44.0        ESE  ...        20.0
142159       NaN         NNW           41.0         NE  ...        20.0
142160       NaN          SE           24.0          S  ...        27.0
142161       NaN           E           41.0        ESE  ...        29.0
142164       NaN           W           28.0        SSW  ...        16.0
142168       NaN           E           46.0          E  ...        32.0
142169       NaN           E           43.0          E  ...        22.0
142170       NaN           E           37.0        ESE  ...        18.0
142171       NaN         ENE           39.0        ESE  ...        22.0
142172       NaN           E           31.0        ESE  ...        26.0
142173       NaN           E           37.0        ESE  ...        11.0
142174       NaN           E           43.0        ESE  ...         6.0
142175       NaN           E           43.0        ESE  ...        19.0
142176       NaN          SE           39.0        ESE  ...        26.0
142177       NaN           E           43.0        ESE  ...        23.0
142178       NaN           E           46.0        ESE  ...        29.0
142179       NaN           E           33.0         SE  ...        24.0
142180       NaN           E           46.0        ESE  ...        29.0
142181       NaN         ENE           35.0        ESE  ...        32.0
142182       NaN          SE           22.0         SE  ...        28.0
142183       NaN           S           19.0          S  ...        24.0
142184       NaN           E           24.0         SE  ...        24.0
142185       NaN         ESE           31.0          S  ...        25.0
142186       NaN         ESE           41.0         SE  ...        32.0
142187       NaN           E           35.0        ESE  ...        33.0
142188       NaN           E           31.0        ESE  ...        27.0
142189       NaN           E           31.0         SE  ...        24.0
142190       NaN         NNW           22.0         SE  ...        21.0
142191       NaN           N           37.0         SE  ...        24.0

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
1            1010.6       1007.8       NaN       NaN     17.2     24.3
2            1007.6       1008.7       NaN       2.0     21.0     23.2
3            1017.6       1012.8       NaN       NaN     18.1     26.5
5            1009.2       1005.4       NaN       NaN     20.6     28.9
7            1013.4       1010.1       NaN       NaN     16.3     25.5
8            1008.9       1003.6       NaN       NaN     18.3     30.2
9            1007.0       1005.7       NaN       NaN     20.1     28.2
10           1011.8       1008.7       NaN       NaN     20.4     28.8
13           1001.2       1001.8       NaN       7.0     15.8     19.8
17           1009.4       1009.7       NaN       2.0     15.5     21.0
18           1019.2       1017.1       NaN       NaN     15.8     23.2
19           1019.3       1014.8       NaN       NaN     19.1     27.3
20           1013.6       1008.1       NaN       1.0     24.5     31.6
21           1007.8       1005.7       NaN       NaN     23.8     30.8
23           1012.9       1010.1       NaN       NaN     21.5     31.2
24           1010.9       1007.6       NaN       1.0     23.2     33.0
25           1006.8       1003.6       NaN       1.0     26.6     31.2
26           1005.2       1001.7       NaN       NaN     24.6     32.1
27           1004.8       1004.2       NaN       NaN     21.6     26.1
30           1004.5       1003.2       NaN       NaN     19.7     25.7
31           1014.4       1013.1       NaN       NaN     14.9     22.1
32           1018.7       1014.8       NaN       NaN     17.1     26.5
33           1015.1       1010.3       NaN       NaN     20.7     33.9
34           1012.6       1009.2       NaN       NaN     22.4     34.4
35           1010.9       1006.7       NaN       NaN     23.1     36.8
36           1007.0       1002.7       NaN       NaN     25.2     38.4
37           1011.9       1010.9       NaN       NaN     17.9     27.6
38           1017.8       1013.7       NaN       NaN     17.2     26.6
39           1013.4       1008.1       NaN       NaN     20.2     29.3
40           1009.9       1006.8       NaN       NaN     22.8     30.0
...             ...          ...       ...       ...      ...      ...
142157       1016.7       1012.8       NaN       NaN     12.3     25.2
142158       1015.3       1011.5       NaN       NaN     14.5     28.8
142159       1016.4       1013.9       NaN       NaN     18.6     29.7
142160       1021.4       1017.8       NaN       NaN     15.7     26.8
142161       1022.6       1018.6       NaN       NaN     14.8     25.7
142164       1019.9       1016.9       NaN       NaN     16.6     27.3
142168       1029.2       1025.3       NaN       NaN     11.1     20.2
142169       1029.6       1027.1       NaN       NaN      9.7     18.3
142170       1030.7       1026.7       NaN       NaN      6.8     17.6
142171       1028.7       1024.1       NaN       NaN      8.6     18.9
142172       1026.9       1022.4       NaN       NaN      9.5     18.6
142173       1027.1       1023.9       NaN       NaN     10.3     19.8
142174       1029.8       1025.9       NaN       NaN      7.9     19.9
142175       1029.0       1025.0       NaN       NaN      9.5     20.5
142176       1030.2       1026.7       NaN       NaN      9.1     19.0
142177       1031.8       1027.7       NaN       NaN      8.7     18.9
142178       1031.0       1027.2       NaN       NaN      8.2     17.4
142179       1030.0       1026.2       NaN       NaN      8.0     18.8
142180       1028.5       1025.8       NaN       NaN      8.5     19.2
142181       1027.2       1023.0       NaN       NaN     10.3     20.3
142182       1026.9       1022.8       NaN       NaN      8.9     20.3
142183       1025.0       1021.4       NaN       NaN      8.8     22.1
142184       1023.8       1020.0       NaN       NaN     12.3     23.3
142185       1025.8       1023.0       NaN       NaN     11.2     23.1
142186       1028.1       1024.3       NaN       7.0     11.6     20.0
142187       1027.2       1023.3       NaN       NaN     11.0     20.3
142188       1024.7       1021.2       NaN       NaN      9.4     20.9
142189       1024.6       1020.3       NaN       NaN     10.1     22.4
142190       1023.5       1019.1       NaN       NaN     10.9     24.5
142191       1021.0       1016.8       NaN       NaN     12.5     26.1

        RainToday  RISK_MM  RainTomorrow
1              No      0.0            No
2              No      0.0            No
3              No      1.0            No
5              No      0.0            No
7              No      0.0            No
8              No      1.4           Yes
9             Yes      0.0            No
10             No      2.2           Yes
13            Yes      0.0            No
17            Yes      0.0            No
18             No      0.0            No
19             No      0.0            No
20             No      0.0            No
21             No      0.0            No
23             No      0.0            No
24             No      0.0            No
25             No      0.0            No
26             No      0.0            No
27             No      1.2           Yes
30             No      0.0            No
31             No      0.0            No
32             No      0.0            No
33             No      0.0            No
34             No      0.0            No
35             No      0.0            No
36             No      0.0            No
37             No      0.0            No
38             No      0.0            No
39             No      0.0            No
40             No      0.0            No
...           ...      ...           ...
142157         No      0.0            No
142158         No      0.0            No
142159         No      0.0            No
142160         No      0.0            No
142161         No      0.0            No
142164         No      0.0            No
142168         No      0.0            No
142169         No      0.0            No
142170         No      0.0            No
142171         No      0.0            No
142172         No      0.0            No
142173         No      0.0            No
142174         No      0.0            No
142175         No      0.0            No
142176         No      0.0            No
142177         No      0.0            No
142178         No      0.0            No
142179         No      0.0            No
142180         No      0.0            No
142181         No      0.0            No
142182         No      0.0            No
142183         No      0.0            No
142184         No      0.0            No
142185         No      0.0            No
142186         No      0.0            No
142187         No      0.0            No
142188         No      0.0            No
142189         No      0.0            No
142190         No      0.0            No
142191         No      0.0            No

[53657 rows x 24 columns]>

In [54]:
for i in range(data.shape[1]):
    print('Column: ' + data.columns[i]  + ' Unique values: ' + str(pd.unique(data.iloc[: , i])) )

Column: Date Unique values: ['2008-12-01' '2008-12-02' '2008-12-03' ... '2008-01-29' '2008-01-30'
 '2008-01-31']
Column: Location Unique values: ['Albury' 'BadgerysCreek' 'Cobar' 'CoffsHarbour' 'Moree' 'Newcastle'
 'NorahHead' 'NorfolkIsland' 'Penrith' 'Richmond' 'Sydney' 'SydneyAirport'
 'WaggaWagga' 'Williamtown' 'Wollongong' 'Canberra' 'Tuggeranong'
 'MountGinini' 'Ballarat' 'Bendigo' 'Sale' 'MelbourneAirport' 'Melbourne'
 'Mildura' 'Nhil' 'Portland' 'Watsonia' 'Dartmoor' 'Brisbane' 'Cairns'
 'GoldCoast' 'Townsville' 'Adelaide' 'MountGambier' 'Nuriootpa' 'Woomera'
 'Albany' 'Witchcliffe' 'PearceRAAF' 'PerthAirport' 'Perth' 'SalmonGums'
 'Walpole' 'Hobart' 'Launceston' 'AliceSprings' 'Darwin' 'Katherine'
 'Uluru']
Column: MinTemp Unique values: [13.4  7.4 12.9  9.2 17.5 14.6 14.3  7.7  9.7 13.1 15.9 12.6  9.8 14.1
 13.5 11.2 11.5 17.1 20.5 15.3 16.2 16.9 20.1 19.7 12.5 12.  11.3  9.6
 10.5 12.3 13.7 16.1 14.  17.  17.3 17.2 17.4 19.8 14.9 13.9 18.6 19.3
 24.4 18.8 20.8 15.7 18.5 20.4 21.8 22.3 22.  28.  21.5 21.7 23.5 28.3
 18.4 12.4 13.3 18.  18.7 15.5  8.9 15.  15.4 16.  12.8 13.2 13.8  7.6
  8.3 11.  20.9 16.4 10.   8.8  8.4  9.3 14.4 10.8 10.1  9.1 10.4 12.2
 10.7  7.8  8.1  7.5  8.2 11.6 13.   9.9  3.5  6.6  7.   5.7  6.2  6.
 10.6  8.6  4.5  5.4  2.1  1.8  7.2  4.6  4.2  5.2  4.1  3.2  4.3  3.7
  3.6  6.9 10.3  3.   2.6  5.1  4.4  4.7  6.7  8.   2.2  1.7  2.8  9.
  6.3 -2.  -1.3  2.   0.5  1.2  0.6  0.9  5.   3.9  3.4  0.  -1.5 -1.7
 -0.4  0.1  4.8  5.9  2.9 -0.6 -0.3 -1.   0.8 -0.1  1.3  3.3  6.5 -0.8
  1.9  6.8  2.7  1.6  5.5  7.3  0.2  5.8  7.1  1.1  1.   6.1  nan  5.3
  4.  11.7  8.5  3.8  6.4  9.5 14.5 15.6 17.8 16.7 18.1 12.1 11.4 18.3
 11.9 21.  11.1 18.2 14.2 11.8 13.6 12.7 15.1 22.9 17.6 21.1 19.4 14.8
 16.3 19.6 20.6 24.5 22.6 16.8  8.7 19.2 24.7 17.7 15.2 18.9 17.9 19.5
 20.3 23.  22.5 20.2 16.5  5.6  3.1  1.4 10.2  9.4  0.4  4.9  1.5  2.3
  0.7 -0.5  2.5 -1.2  0.3  2.4 14.7 10.9 16.6 21.3 23.2 21.6 22.1 24.
 19.9 20.7 21.9 -0.7 -1.1 -1.4 -0.2 -1.6 15.8 19.1 20.  -2.5 -1.8  7.9
 21.2 22.2 23.7 25.2 19.  -0.9 -2.1 -2.8 26.  -2.4 26.8 23.4 22.8 22.4
 24.6 23.9 -3.  23.1 23.6 21.4 -1.9 25.1 24.2 27.1 23.3 24.9 25.4 23.8
 27.  26.2 25.  24.8 27.6 24.1 27.2 29.1 28.9 25.3 27.4 28.8 27.3 26.1
 26.5 22.7 25.7 24.3 29.3 27.7 26.3 25.8 29.4 25.6 26.7 26.6 28.1 27.8
 28.5 25.5 26.9 26.4 27.5 28.7 29.7 25.9 -2.3 -3.3 -2.2 -3.2 29.  28.6
 -3.8 -4.8 -3.1 -2.7 -2.6 -2.9 -4.7 -3.6 -3.5 -3.4 -5.3 -3.7 -5.8 -5.
 -4.5 -4.3 -3.9 -4.2 -4.  -6.9 -6.5 -5.5 -5.2 -6.3 -4.4 -8.  -6.7 -4.9
 -5.4 -6.1 -4.6 -6.  -6.6 -5.1 -5.6 -6.8 -7.6 -7.  -4.1 -5.7 -6.2 -8.2
 -5.9 -8.5 -7.1 -6.4 -7.5 -7.2 -7.8 -7.3 30.5 29.8 31.9 28.4 28.2 27.9
 30.7 33.9 29.2 29.9 31.4 31.8 29.5 31.2 29.6 30.3 31.  30.2]
Column: MaxTemp Unique values: [22.9 25.1 25.7 28.  32.3 29.7 25.  26.7 31.9 30.1 30.4 21.7 18.6 21.
 27.7 20.9 22.5 25.6 29.3 33.  31.8 30.9 32.4 33.9 32.7 27.2 24.2 24.4
 26.5 23.9 28.8 34.6 35.8 37.9 38.9 28.3 28.4 30.8 32.  34.7 37.7 43.
 32.2 36.6 39.9 38.1 34.  35.2 30.6 34.3 38.4 38.2 40.7 41.5 42.9 42.7
 43.1 38.3 36.9 41.2 42.2 44.8 40.2 31.2 27.3 21.6 29.  29.2 31.3 31.1
 29.1 31.7 33.2 29.6 32.6 34.5 30.3 22.1 22.  24.  27.9 30.2 30.5 25.8
 27.  19.7 21.9 25.3 33.5 33.6 30.  31.6 22.3 29.8 27.6 28.9 29.9 32.1
 28.1 21.4 24.9 25.4 20.  23.4 22.7 16.2 15.8 12.9 11.5 14.5 12.2 16.5
 17.  19.2 18.9 19.1 18.8 19.3 18.4 19.  20.5 19.5 17.7 18.5 15.1 16.3
 16.6 16.4 15.6 19.8 21.1 20.3 18.1 15.7 16.8 17.1 14.3 13.4 17.4 16.1
 10.5 11.6 12.   8.8  9.6  8.2 12.4 14.9 15.9 14.7 15.3 17.3 15.5 14.1
 13.7 11.9 12.3 13.3 13.2 12.1 12.5 13.8 15.  13.5 13.1 11.  12.6 14.4
  9.8 12.7 13.9 14.8 15.2 17.5 13.6 12.8 16.7 17.9 11.1 14.2 20.7 16.9
 17.6 24.7 17.8 17.2 20.4 20.6 20.2 18.2 18.7 23.3 26.6 27.1 23.1 24.1
 26.8 26.9 24.3 23.2 33.4 36.  35.1 32.8 35.4 36.3 39.7 23.6 32.9 26.2
 26.4 31.5 27.5 30.7 27.4 22.6 38.6 40.3 33.7 35.9 36.8 33.8 36.4 39.8
 42.4 25.2 37.3 41.8 34.4 36.5 35.6 26.1 28.5 31.  26.3  nan 25.5 22.4
 28.6 31.4 28.7 24.8 19.9 23.5 25.9 23.  10.2 14.   8.4  8.3  9.4 10.9
 10.3 10.8 14.6 15.4 10.  10.1 11.8 16.  10.4 13.  11.7 10.7 19.6 20.1
 20.8 23.7 18.  21.8 22.2 24.5 29.4 21.2 32.5 28.2 21.5 22.8 11.2 19.4
 18.3  9.2  9.3 21.3 23.8 26.  24.6 27.8 33.1 34.9 36.1 36.2 35.3 35.5
  9.7 10.6 11.3 11.4 36.7 37.4 43.4 42.  40.4 39.2 38.8 37.  35.7 37.1
 29.5 37.6 40.5 39.  43.6 42.6 34.2 33.3 40.6 41.7 41.6 41.1 40.1  8.7
 39.6 34.1  9.9  8.6  9.1  6.8  9.5  9.  37.2 34.8 40.  35.  38.  39.5
 40.9 38.5  7.5 39.3 42.5 43.7 37.8 38.7 41.9 39.4 41.4 37.5 45.8 41.
 39.1 40.8 42.8 45.1 44.4 43.5 42.1 46.4 43.9 45.4 41.3 44.3 46.  43.8
 43.2 45.2  8.5 42.3  7.8 45.7 46.6 47.3 44.5 44.1 44.  43.3 46.5 44.9
 46.9 45.3 44.6 47.   8.9  8.1  7.6  6.3  8.   6.6 45.5  4.1  7.7  7.1
  7.9  7.   7.3  2.6  7.4  6.2  7.2  6.   4.9 -1.7  0.   2.4  5.3  2.3
  5.7  5.2  5.5  4.7  6.5  2.5  2.7  3.4  2.9  5.   3.2  0.1 -0.1 -2.2
 -0.6  0.6  2.2  4.   3.5  3.   4.2  3.3  3.9  0.4  5.9 -0.7 -1.8 -0.2
 -1.3  1.8  3.1  1.6  0.3  1.2 -0.5  1.   0.5  0.2  1.9  2.   5.1  2.8
  6.7  0.9  3.8  4.3 -2.4 -0.3  4.6  6.9 -2.5  2.1  1.4  5.6  3.6  4.4
 -2.7 -1.   5.8 -1.4 -0.8 -2.   4.5  1.7 -0.9 -2.1 -1.5 -3.1  1.1 -1.2
  4.8  6.1  6.4  3.7 -1.1  1.5  5.4  1.3  0.8 -2.3 -3.7 -2.9 -0.4 -1.9
 -3.8  0.7 -4.1 -3.2 -3.  -4.8 44.2 46.8 46.7 45.  46.3 44.7 45.6 46.2
 48.1 46.1]
Column: Rainfall Unique values: [6.000e-01 0.000e+00 1.000e+00 2.000e-01 1.400e+00 2.200e+00 1.560e+01
 3.600e+00       nan 1.680e+01 1.060e+01 1.200e+00 8.000e-01 6.400e+00
 4.000e-01 3.000e+00 5.800e+00 1.160e+01 1.800e+00 8.600e+00 1.260e+01
 8.400e+00 6.200e+00 2.000e+01 2.100e+01 3.200e+00 4.800e+00 4.200e+00
 8.000e+00 1.440e+01 4.600e+00 2.000e+00 5.600e+00 1.600e+00 6.000e+00
 4.400e+00 5.400e+00 5.000e+00 7.800e+00 6.800e+00 9.800e+00 3.800e+00
 2.400e+00 5.200e+00 6.600e+00 1.340e+01 1.020e+01 2.880e+01 7.000e+00
 2.580e+01 9.400e+00 1.240e+01 5.220e+01 2.060e+01 6.600e+01 1.100e+01
 1.700e+01 1.040e+01 2.800e+01 2.140e+01 1.860e+01 7.200e+00 8.200e+00
 1.080e+01 1.540e+01 9.600e+00 4.000e+00 2.180e+01 2.080e+01 2.480e+01
 1.000e+01 1.140e+01 1.900e+01 2.220e+01 3.280e+01 3.400e+00 5.080e+01
 5.260e+01 1.920e+01 1.880e+01 1.480e+01 1.200e+01 1.840e+01 2.560e+01
 3.500e+01 1.420e+01 1.380e+01 2.600e+00 9.920e+01 5.100e+01 3.980e+01
 2.820e+01 1.220e+01 1.280e+01 1.180e+01 1.980e+01 1.740e+01 8.800e+00
 1.620e+01 1.460e+01 2.800e+00 3.080e+01 2.840e+01 3.480e+01 4.400e+01
 1.400e+01 1.660e+01 9.000e+00 2.680e+01 3.840e+01 1.042e+02 3.660e+01
 3.420e+01 2.940e+01 2.720e+01 1.120e+01 1.320e+01 3.340e+01 7.600e+00
 2.460e+01 7.400e+00 1.600e+01 1.940e+01 5.340e+01 1.500e+01 3.360e+01
 1.720e+01 3.740e+01 1.300e+01 3.100e+01 9.200e+00 6.620e+01 3.640e+01
 4.100e+01 2.440e+01 2.700e+01 4.680e+01 1.580e+01 3.580e+01 2.240e+01
 1.640e+01 1.520e+01 2.300e+01 2.280e+01 2.860e+01 4.600e+01 2.420e+01
 2.200e+01 1.800e+01 3.120e+01 2.120e+01 3.600e+01 2.340e+01 3.200e+01
 4.640e+01 1.360e+01 4.200e+01 3.380e+01 2.540e+01 2.040e+01 2.260e+01
 4.320e+01 6.140e+01 4.820e+01 4.860e+01 1.820e+01 6.780e+01 3.920e+01
 3.180e+01 8.240e+01 3.540e+01 1.160e+02 3.060e+01 1.780e+01 3.820e+01
 3.020e+01 2.400e+01 4.700e+01 4.240e+01 3.300e+01 4.000e+01 4.420e+01
 3.460e+01 3.040e+01 3.880e+01 8.360e+01 5.020e+01 2.620e+01 3.800e+01
 3.160e+01 2.780e+01 2.980e+01 1.760e+01 1.002e+02 1.092e+02 2.360e+01
 3.260e+01 2.160e+01 5.400e+01 3.960e+01 2.600e+01 3.400e+01 4.940e+01
 3.700e+01 2.920e+01 6.800e+01 3.320e+01 2.740e+01 3.900e+01 3.860e+01
 4.300e+01 4.500e+00 2.910e+01 2.900e+00 1.300e+00 3.000e+01 6.360e+01
 1.890e+02 5.860e+01 5.900e+01 2.020e+01 4.280e+01 7.600e+01 1.960e+01
 5.580e+01 7.000e+01 7.120e+01 1.418e+02 9.600e+01 3.710e+02 5.800e+01
 6.700e+01 8.060e+01 5.660e+01 4.520e+01 5.940e+01 4.260e+01 3.440e+01
 9.000e+01 1.280e+02 6.120e+01 2.380e+01 2.760e+01 7.380e+01 7.220e+01
 1.054e+02 4.040e+01 1.020e+02 4.440e+01 4.800e+01 6.380e+01 3.680e+01
 5.500e+00 2.520e+01 1.034e+02 1.276e+02 6.320e+01 5.240e+01 2.500e+01
 5.500e+01 5.680e+01 7.080e+01 6.240e+01 1.120e+02 1.532e+02 4.580e+01
 9.700e+01 5.180e+01 8.640e+01 5.000e-01 1.598e+02 2.085e+02 1.722e+02
 9.000e-01 2.500e+00 3.000e-01 1.700e+00 3.300e+00 5.120e+01 1.064e+02
 1.478e+02 4.560e+01 5.960e+01 2.900e+01 1.170e+01 7.500e+01 7.640e+01
 6.400e+01 5.320e+01 1.004e+02 1.000e-01 6.580e+01 8.500e+00 3.240e+01
 1.578e+02 4.100e+00 1.138e+02 7.000e-01 3.100e+00 1.500e+00 3.220e+01
 3.270e+01 1.010e+01 1.110e+01 9.610e+01 4.980e+01 2.196e+02 1.094e+02
 3.500e+00 2.640e+01 2.960e+01 3.620e+01 3.760e+01 4.380e+01 4.150e+01
 5.060e+01 1.428e+02 1.062e+02 1.048e+02 2.700e+00 3.110e+01 1.390e+01
 7.100e+01 9.060e+01 6.480e+01 4.760e+01 5.140e+01 2.660e+01 4.880e+01
 3.720e+01 3.940e+01 1.130e+02 7.440e+01 9.280e+01 4.020e+01 7.680e+01
 5.460e+01 4.480e+01 4.460e+01 5.000e+01 2.270e+01 2.090e+01 5.980e+01
 4.540e+01 1.472e+02 3.520e+01 7.140e+01 3.140e+01 2.370e+01 4.220e+01
 7.560e+01 4.180e+01 4.360e+01 4.900e+00 3.560e+01 2.650e+01 4.900e+01
 3.390e+01 3.070e+01 5.300e+00 1.070e+01 6.410e+01 5.040e+01 4.550e+01
 6.900e+00 6.880e+01 7.760e+01 8.980e+01 6.980e+01 3.250e+01 6.260e+01
 1.325e+02 1.570e+01 2.250e+01 2.400e+02 4.120e+01 6.300e+00 5.820e+01
 3.790e+01 2.950e+01 5.200e+01 2.150e+01 2.163e+02 1.250e+01 2.300e+00
 5.160e+01 2.070e+01 6.340e+01 7.420e+01 2.320e+01 4.340e+01 5.600e+01
 4.780e+01 4.840e+01 6.920e+01 5.560e+01 6.180e+01 7.300e+01 8.340e+01
 3.780e+01 1.264e+02 4.720e+01 5.920e+01 1.202e+02 5.620e+01 8.900e+01
 7.620e+01 8.280e+01 6.960e+01 7.200e+01 4.080e+01 1.074e+02 7.160e+01
 2.990e+01 1.422e+02 7.980e+01 8.480e+01 1.056e+02 5.760e+01 4.500e+01
 6.220e+01 1.110e+02 4.060e+01 1.226e+02 5.480e+01 6.100e+01 6.160e+01
 1.568e+02 3.990e+01 2.100e+00 1.900e+00 1.100e+00 4.700e+00 5.700e+00
 9.220e+01 1.154e+02 1.018e+02 4.960e+01 8.560e+01 8.140e+01 8.160e+01
 6.760e+01 5.840e+01 4.160e+01 5.640e+01 1.118e+02 4.740e+01 1.134e+02
 7.400e+01 7.060e+01 7.840e+01 6.860e+01 7.740e+01 7.320e+01 9.940e+01
 6.520e+01 8.820e+01 5.740e+01 9.520e+01 5.700e+01 1.194e+02 1.058e+02
 5.440e+01 4.140e+01 9.440e+01 6.440e+01 9.380e+01 6.840e+01 5.280e+01
 8.500e+01 8.320e+01 1.060e+02 6.020e+01 9.100e+01 5.360e+01 1.046e+02
 8.040e+01 1.068e+02 8.860e+01 7.280e+01 6.280e+01 4.660e+01 9.560e+01
 5.300e+01 5.420e+01 1.108e+02 5.780e+01 1.230e+01 2.290e+01 1.330e+01
 1.348e+02 8.440e+01 4.620e+01 6.420e+01 8.680e+01 1.576e+02 1.668e+02
 1.560e+02 1.144e+02 8.180e+01 2.250e+02 8.700e+00 9.140e+01 1.810e+01
 4.920e+01 6.080e+01 9.720e+01 8.260e+01 7.860e+01 5.380e+01 7.260e+01
 1.390e+02 5.880e+01 6.500e+01 7.900e+01 7.580e+01 5.520e+01 1.920e+02
 8.080e+01 1.180e+02 9.640e+01 1.642e+02 6.940e+01 7.520e+01 5.540e+01
 8.700e+01 9.300e+01 9.160e+01 8.420e+01 8.760e+01 7.800e+01 7.340e+01
 1.022e+02 6.040e+01 8.940e+01 1.076e+02 8.380e+01 7.820e+01 8.800e+01
 6.640e+01 8.220e+01 1.550e+02 6.000e+01 6.560e+01 6.300e+01 8.400e+01
 8.740e+01 8.300e+01 7.360e+01 7.720e+01 7.940e+01 1.214e+02 6.060e+01
 9.360e+01 1.684e+02 1.450e+02 9.400e+01 8.920e+01 6.820e+01 1.826e+02
 1.106e+02 9.800e+01 2.784e+02 1.402e+02 6.200e+01 1.216e+02 7.180e+01
 1.158e+02 7.920e+01 2.686e+02 1.830e+02 1.096e+02 1.282e+02 2.062e+02
 1.366e+02 1.502e+02 1.616e+02 1.090e+02 1.152e+02 1.752e+02 2.472e+02
 8.540e+01 1.052e+02 7.480e+01 1.150e+02 1.260e+02 8.460e+01 1.580e+02
 7.780e+01 6.460e+01 1.182e+02 1.438e+02 1.186e+02 1.122e+02 1.782e+02
 1.834e+02 1.082e+02 1.112e+02 1.284e+02 8.020e+01 1.290e+02 1.050e+02
 1.776e+02 8.620e+01 2.368e+02 9.340e+01 7.960e+01 2.068e+02 8.120e+01
 9.260e+01 1.652e+02 1.704e+02 9.320e+01 9.820e+01 1.486e+02 7.020e+01
 1.442e+02 1.646e+02 1.746e+02 7.040e+01 8.780e+01 1.248e+02 1.208e+02
 7.880e+01 7.660e+01 1.190e+01 9.500e+00 1.050e+01 7.100e+00 6.500e+00
 6.100e+00 3.430e+01 3.900e+00 6.700e+00 1.270e+01 1.450e+01 2.930e+01
 2.390e+01 8.900e+00 9.100e+00 1.310e+01 1.090e+01 1.850e+01 6.540e+01
 4.730e+01 5.900e+00 1.970e+01 1.210e+01 1.150e+01 7.500e+00 7.900e+00
 2.530e+01 1.750e+01 7.300e+00 9.900e+00 1.550e+01 1.590e+01 8.100e+01
 9.580e+01 9.040e+01 1.412e+02 1.622e+02 1.364e+02 1.314e+02 1.326e+02
 3.676e+02 1.846e+02 1.822e+02 1.452e+02 9.680e+01 7.460e+01 1.294e+02
 1.228e+02 1.098e+02 1.456e+02 2.106e+02 1.176e+02 6.950e+01 1.670e+02
 6.900e+01]
Column: Evaporation Unique values: [     nan 1.20e+01 1.48e+01 1.26e+01 1.08e+01 1.14e+01 1.12e+01 1.30e+01
 9.80e+00 1.46e+01 1.10e+01 1.28e+01 1.38e+01 1.64e+01 1.74e+01 1.60e+01
 1.36e+01 8.00e+00 8.20e+00 8.60e+00 1.42e+01 1.58e+01 1.62e+01 1.34e+01
 1.44e+01 1.18e+01 1.56e+01 1.52e+01 1.16e+01 9.60e+00 6.60e+00 6.00e-01
 6.00e+00 3.00e+00 2.00e+00 5.20e+00 9.00e+00 1.02e+01 1.00e+01 7.40e+00
 8.40e+00 9.20e+00 9.40e+00 1.24e+01 1.04e+01 7.20e+00 6.80e+00 7.60e+00
 4.40e+00 6.40e+00 7.80e+00 7.00e+00 8.80e+00 6.20e+00 5.80e+00 2.00e-01
 2.40e+00 1.80e+00 2.20e+00 2.80e+00 5.00e+00 5.60e+00 4.80e+00 4.20e+00
 4.00e+00 3.20e+00 4.60e+00 3.40e+00 3.60e+00 0.00e+00 1.40e+00 3.80e+00
 8.00e-01 2.60e+00 1.60e+00 1.20e+00 1.00e+00 5.40e+00 1.06e+01 1.68e+01
 1.70e+01 2.02e+01 1.40e+01 1.72e+01 1.22e+01 1.50e+01 1.82e+01 1.32e+01
 4.10e+00 1.70e+00 4.00e-01 1.90e+00 6.48e+01 3.20e+01 2.62e+01 2.46e+01
 2.33e+01 1.54e+01 3.26e+01 3.04e+01 3.44e+01 1.80e+01 4.94e+01 1.88e+01
 1.90e+01 1.84e+01 8.10e+00 4.90e+00 2.52e+01 2.40e+01 2.24e+01 1.66e+01
 4.88e+01 5.62e+01 3.70e+01 5.24e+01 1.76e+01 6.30e+00 2.00e+01 2.14e+01
 2.50e+01 1.78e+01 2.56e+01 1.86e+01 2.16e+01 3.54e+01 2.30e+01 2.20e+01
 3.08e+01 1.11e+01 1.98e+01 3.32e+01 8.62e+01 6.58e+01 5.64e+01 3.12e+01
 2.18e+01 5.70e+00 2.70e+00 1.30e+00 2.50e+00 3.30e+00 9.90e+00 2.30e+00
 7.00e-01 2.10e+00 1.10e+00 2.90e+00 1.50e+00 3.10e+00 6.10e+00 1.96e+01
 9.70e+00 1.05e+01 5.90e+00 9.30e+00 2.04e+01 1.21e+01 3.06e+01 2.42e+01
 3.00e-01 4.72e+01 1.92e+01 3.84e+01 3.46e+01 2.36e+01 4.42e+01 3.22e+01
 3.14e+01 3.42e+01 2.06e+01 2.68e+01 2.26e+01 2.38e+01 3.86e+01 2.64e+01
 4.68e+01 4.24e+01 4.66e+01 6.02e+01 3.76e+01 3.64e+01 4.84e+01 4.36e+01
 3.50e+01 5.04e+01 3.58e+01 5.40e+01 4.12e+01 3.28e+01 3.56e+01 3.10e+01
 3.24e+01 1.94e+01 6.08e+01 2.74e+01 4.34e+01 2.70e+01 3.68e+01 2.54e+01
 5.72e+01 2.86e+01 3.36e+01 3.74e+01 2.34e+01 4.30e+01 3.62e+01 3.16e+01
 3.92e+01 2.58e+01 6.54e+01 4.04e+01 2.60e+01 2.12e+01 7.10e+00 7.48e+01
 3.72e+01 2.88e+01 5.30e+00 4.70e+00 8.70e+00 3.90e+00 3.50e+00 9.50e+00
 9.00e-01 3.02e+01 1.47e+01 1.31e+01 7.50e+00 8.30e+00 5.10e+00 3.70e+00
 5.50e+00 1.81e+01 4.30e+00 2.10e+01 3.38e+01 4.50e+00 2.05e+01 1.19e+01
 6.90e+00 7.70e+00 9.10e+00 1.09e+01 1.97e+01 1.01e+01 6.70e+00 5.00e-01
 1.39e+01 1.25e+01 1.00e-01 1.45e+01 1.91e+01 1.71e+01 7.30e+00 2.51e+01
 2.22e+01 2.72e+01 1.93e+01 6.50e+00 2.76e+01 1.15e+01 2.28e+01 2.84e+01
 2.08e+01 3.94e+01 2.78e+01 2.82e+01 2.66e+01 3.30e+01 2.98e+01 2.32e+01
 3.34e+01 2.80e+01 3.80e+01 4.00e+01 2.92e+01 2.94e+01 3.88e+01 6.44e+01
 3.00e+01 2.44e+01 2.48e+01 5.54e+01 5.92e+01 1.45e+02 4.70e+01 8.90e+00
 1.35e+01 8.50e+00 1.13e+01 4.40e+01 7.90e+00 4.44e+01 2.21e+01 3.66e+01
 3.60e+01 3.40e+01 1.49e+01 4.26e+01 1.43e+01 1.03e+01 1.17e+01 1.07e+01
 8.12e+01 6.30e+01 7.00e+01 5.48e+01 5.98e+01 7.22e+01 6.40e+01 5.96e+01
 5.90e+01 4.23e+01 1.27e+01 1.77e+01 2.25e+01 1.53e+01 3.52e+01 3.45e+01
 2.31e+01 4.22e+01 8.24e+01 4.20e+01 4.32e+01 6.20e+01 7.73e+01 1.33e+01
 5.52e+01 5.80e+01 5.76e+01 5.56e+01 4.62e+01 5.50e+01 5.08e+01 5.10e+01
 6.88e+01 5.16e+01 5.85e+01 5.58e+01 5.36e+01 2.55e+01 5.60e+01 4.80e+01
 7.04e+01 5.94e+01 5.66e+01 1.41e+01 1.23e+01 1.51e+01 1.65e+01 4.18e+01
 4.08e+01 5.02e+01 4.16e+01 4.28e+01 3.96e+01]
Column: Sunshine Unique values: [ nan 12.3 13.  13.3 10.6 12.2  8.4  0.  12.6 13.2 12.7 12.1 10.3 13.1
 12.9 11.3  6.9 10.9  3.7  5.9 10.5 12.4 13.4 13.6  7.4 10.   2.3  6.6
  0.3 10.7 11.6 10.2  9.  12.   3.   7.9 11.5 11.2  4.8  5.8  6.  11.1
 11.8 11.4 10.8  7.8 11.   5.5  4.7  4.2  4.4  6.2  9.8  9.9  4.3  8.
  9.6 10.4  9.3  8.7  7.6  7.5 10.1  6.3  2.8  0.7  9.4  9.7  0.6  5.1
  8.3  4.1  3.9  6.8  8.6  2.7  8.2  3.1  1.8  0.1  0.8  3.4  7.1  5.
  5.7  6.1  7.   2.9  2.5  4.6  8.9  9.1  1.7  8.1  9.5  1.2  1.4  8.8
  2.2  3.5  9.2  1.9 11.7 11.9  7.7  0.9 12.5  2.1 12.8 13.7  8.5  0.2
  4.   2.4  5.2  0.5  6.4  4.5  1.1  2.   0.4  1.5  3.3  6.5  2.6  3.8
  3.6  3.2  6.7  5.4  7.2  4.9  1.   1.6  5.3  7.3  5.6  1.3 13.8 13.5
 14.  13.9 14.1 14.5 14.3 14.2]
Column: WindGustDir Unique values: ['W' 'WNW' 'WSW' 'NE' 'NNW' 'N' 'NNE' 'SW' 'ENE' 'SSE' 'S' 'NW' 'SE' 'ESE'
 nan 'E' 'SSW']
Column: WindGustSpeed Unique values: [ 44.  46.  24.  41.  56.  50.  35.  80.  28.  30.  31.  61.  22.  63.
  43.  26.  33.  57.  48.  39.  37.  52.  98.  54.  83.  nan  59.  70.
  69.  17.  20.  19.  15.  13.  11.  72.  85.  65.  78. 107.  74.  67.
  94.  76.  81.  87.   9.   7.  89.  91.  93. 102. 100. 113. 117.  96.
 111. 106. 135. 104. 120. 115. 126. 109. 122. 124. 130.   6.]
Column: WindDir9am Unique values: ['W' 'NNW' 'SE' 'ENE' 'SW' 'SSE' 'S' 'NE' nan 'SSW' 'N' 'WSW' 'ESE' 'E'
 'NW' 'WNW' 'NNE']
Column: WindDir3pm Unique values: ['WNW' 'WSW' 'E' 'NW' 'W' 'SSE' 'ESE' 'ENE' 'NNW' 'SSW' 'SW' 'SE' 'N' 'S'
 'NNE' nan 'NE']
Column: WindSpeed9am Unique values: [ 20.   4.  19.  11.   7.   6.  15.  17.  28.  24.  nan   9.   0.  13.
   2.  26.  30.  22.  35.  37.  31.  33.  48.  39.  44.  41.  46.  43.
  56.  83.  74.  52.  65.  50. 130.  54.  61.  57.  59.  87.  67.  63.
  69.  72.]
Column: WindSpeed3pm Unique values: [24. 22. 26.  9. 20. 17. 28. 11.  6. 13. 19. 30. 31.  7. 15. 48.  4. 33.
  0.  2. nan 37. 46. 39. 50. 35. 44. 41. 43. 56. 61. 54. 52. 83. 65. 78.
 57. 63. 59. 74. 72. 69. 76. 87. 67.]
Column: Humidity9am Unique values: [ 71.  44.  38.  45.  82.  55.  49.  48.  42.  58.  89.  76.  65.  50.
  69.  80.  47.  56.  54.  41.  78.  46.  43.  33.  34.  36.  52.  51.
  40.  35.  39.  60.  37.  27.  32.  53.  20.  66.  63.  57.  62.  87.
  61.  59.  92.  72.  67.  75.  88.  68.  73.  74.  83.  77.  70.  81.
  86.  97.  99.  91.  85.  93.  84.  94.  79.  98.  96.  95.  90.  64.
  29.  21. 100.  24.  nan  25.  31.  18.  23.  26.  28.  30.  19.  22.
  17.  15.   9.  12.  13.  16.   6.  10.  14.  11.   7.   8.   5.   3.
   2.   4.   0.   1.]
Column: Humidity3pm Unique values: [ 22.  25.  30.  16.  33.  23.  19.   9.  27.  91.  93.  43.  28.  82.
  65.  32.  26.  24.  17.  15.  70.  12.   8.  31.  20.  10.  21.  39.
  13.  11.  69.  18.  14.  35.  90.  68.  74.  41.  34.  78.  49.  37.
  42.  47.  52.  29.  86.  89.  62.  79.  48.  46.  38.  44.  51.  36.
  45.  40.  53.  61.  59.  63.  54.  57.  50.  58.  75.  97.  80.  95.
  56.  72.  60.  71.  73.  81.  76.  64.  87.  85.  67.  55.  77.  84.
   7.  99.  92.  66.  83.  94.  96.  88.  nan 100.  98.   5.   6.   1.
   4.   2.   3.   0.]
Column: Pressure9am Unique values: [1007.7 1010.6 1007.6 1017.6 1010.8 1009.2 1009.6 1013.4 1008.9 1007.
 1011.8 1010.5  994.3 1001.2 1012.2 1005.8 1009.4 1019.2 1019.3 1013.6
 1007.8 1011.  1012.9 1010.9 1006.8 1005.2 1004.8 1005.6 1006.1 1004.5
 1014.4 1018.7 1015.1 1012.6 1011.9 1017.8 1009.9 1014.1 1015.7 1011.6
 1008.4 1019.7 1015.8 1010.1 1005.3 1007.9 1005.4 1016.5 1017.7 1014.9
 1014.6 1014.2 1012.5 1011.7 1008.8 1005.9 1008.  1008.2 1009.3 1012.8
 1017.  1023.3 1022.5 1016.2 1017.2 1012.4 1015.6 1013.  1014.  1016.6
 1007.5 1014.7 1014.5 1013.7 1015.2 1019.5 1021.3 1017.4 1012.7 1013.3
 1016.3 1014.8 1019.1 1023.  1023.8 1022.4 1023.2 1022.6 1018.8 1019.8
 1020.4 1021.8 1026.7 1027.1 1024.2 1021.5 1024.4 1024.1 1018.5 1022.8
 1022.7 1023.6 1025.2 1026.  1004.  1013.8 1018.  1023.1 1023.4 1026.9
 1028.7 1029.8 1031.4 1028.5 1026.2 1028.8 1025.1 1025.6 1022.3 1018.4
 1015.3 1015.  1024.7 1022.2 1025.  1024.6 1021.4 1021.7 1030.3 1034.1
 1031.9 1029.3 1023.5 1021.  1017.9 1011.1 1025.7 1018.3 1013.9 1029.7
 1031.6 1030.8 1021.9 1020.7 1020.2 1015.5 1011.4 1006.5 1008.6 1019.9
 1030.4 1032.  1020.5 1010.4 1006.6 1021.6 1009.5 1027.3 1026.8 1024.
 1025.8 1027.9 1026.4 1018.6 1009.  1011.5 1021.1 1021.2 1018.2 1027.7
 1012.  1004.1 1016.1 1016.9 1002.6 1018.9 1024.9 1005.  1020.   997.8

In [55]:
# percentage of missing values
data.isna().sum() / data.shape[0]

Date             0.000000
Location         0.000000
MinTemp          0.004480
MaxTemp          0.002265
Rainfall         0.009888
Evaporation      0.427890
Sunshine         0.476929
WindGustDir      0.065615
WindGustSpeed    0.065193
WindDir9am       0.070418
WindDir3pm       0.026570
WindSpeed9am     0.009480
WindSpeed3pm     0.018496
Humidity9am      0.012476
Humidity3pm      0.025388
Pressure9am      0.098556
Pressure3pm      0.098324
Cloud9am         0.377353
Cloud3pm         0.401525
Temp9am          0.006358
Temp3pm          0.019171
RainToday        0.009888
RISK_MM          0.000000
RainTomorrow     0.000000
dtype: float64

In [56]:
pd.unique(data['Location'])

array(['Albury', 'BadgerysCreek', 'Cobar', 'CoffsHarbour', 'Moree',
       'Newcastle', 'NorahHead', 'NorfolkIsland', 'Penrith', 'Richmond',
       'Sydney', 'SydneyAirport', 'WaggaWagga', 'Williamtown',
       'Wollongong', 'Canberra', 'Tuggeranong', 'MountGinini', 'Ballarat',
       'Bendigo', 'Sale', 'MelbourneAirport', 'Melbourne', 'Mildura',
       'Nhil', 'Portland', 'Watsonia', 'Dartmoor', 'Brisbane', 'Cairns',
       'GoldCoast', 'Townsville', 'Adelaide', 'MountGambier', 'Nuriootpa',
       'Woomera', 'Albany', 'Witchcliffe', 'PearceRAAF', 'PerthAirport',
       'Perth', 'SalmonGums', 'Walpole', 'Hobart', 'Launceston',
       'AliceSprings', 'Darwin', 'Katherine', 'Uluru'], dtype=object)

In [57]:
data.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null object
RISK_MM          142193 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(17), object(7)
memory usage: 26.0+ MB

In [59]:
data = data.drop('RISK_MM', axis=1)

In [60]:
data.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [61]:
import numpy as np

In [62]:
## Assume cloud = nan means 0
data[data['Cloud9am'] == np.nan ] = 0

In [63]:
data[data['Cloud3pm'] == np.nan ] = 0

In [64]:
# lets remove all columns with greater than 35% missing values

In [65]:
list(data.columns)

['Date',
 'Location',
 'MinTemp',
 'MaxTemp',
 'Rainfall',
 'Evaporation',
 'Sunshine',
 'WindGustDir',
 'WindGustSpeed',
 'WindDir9am',
 'WindDir3pm',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Cloud9am',
 'Cloud3pm',
 'Temp9am',
 'Temp3pm',
 'RainToday',
 'RainTomorrow']

In [66]:
df = data

In [67]:
for column in list(data.columns):
    if (df[df[column].isna()].shape[0] / df.shape[0]) > 0.35 : 
        print ('+1')
        print(column)
        df = df.drop(column, axis =1)

+1
Evaporation
+1
Sunshine
+1
Cloud9am
+1
Cloud3pm

In [68]:
# RiSK MM would give hinsight so let's remove it
df = df.drop('RISK_MM', axis =1)

KeyError: "['RISK_MM'] not found in axis"

In [69]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No

In [70]:
 df.isna().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Temp9am            904
Temp3pm           2726
RainToday         1406
RainTomorrow         0
dtype: int64

In [71]:
# to fill Rain Today let's find out the mode for that month of this column

In [72]:
# lets add a month column

In [73]:
(df.Date[1]).split('-')[1]

'12'

In [74]:
df['Date'].apply(lambda x: x.split('-'))

0         [2008, 12, 01]
1         [2008, 12, 02]
2         [2008, 12, 03]
3         [2008, 12, 04]
4         [2008, 12, 05]
5         [2008, 12, 06]
6         [2008, 12, 07]
7         [2008, 12, 08]
8         [2008, 12, 09]
9         [2008, 12, 10]
10        [2008, 12, 11]
11        [2008, 12, 12]
12        [2008, 12, 13]
13        [2008, 12, 14]
14        [2008, 12, 16]
15        [2008, 12, 17]
16        [2008, 12, 18]
17        [2008, 12, 19]
18        [2008, 12, 20]
19        [2008, 12, 21]
20        [2008, 12, 22]
21        [2008, 12, 23]
22        [2008, 12, 24]
23        [2008, 12, 25]
24        [2008, 12, 26]
25        [2008, 12, 27]
26        [2008, 12, 28]
27        [2008, 12, 29]
28        [2008, 12, 30]
29        [2008, 12, 31]
               ...
142163    [2017, 05, 26]
142164    [2017, 05, 27]
142165    [2017, 05, 28]
142166    [2017, 05, 29]
142167    [2017, 05, 30]
142168    [2017, 05, 31]
142169    [2017, 06, 01]
142170    [2017, 06, 02]
142171    [2017, 06, 03]
142172    [2017, 06, 04]
142173    [2017, 06, 05]
142174    [2017, 06, 06]
142175    [2017, 06, 07]
142176    [2017, 06, 08]
142177    [2017, 06, 09]
142178    [2017, 06, 10]
142179    [2017, 06, 11]
142180    [2017, 06, 12]
142181    [2017, 06, 13]
142182    [2017, 06, 14]
142183    [2017, 06, 15]
142184    [2017, 06, 16]
142185    [2017, 06, 17]
142186    [2017, 06, 18]
142187    [2017, 06, 19]
142188    [2017, 06, 20]
142189    [2017, 06, 21]
142190    [2017, 06, 22]
142191    [2017, 06, 23]
142192    [2017, 06, 24]
Name: Date, Length: 142193, dtype: object

In [75]:
df['Month'] = df['Date'].apply(lambda x: x.split('-')[1])

In [76]:
df['Year'] = df['Date'].apply(lambda x: x.split('-')[0])

In [77]:
df['Day'] = df['Date'].apply(lambda x: x.split('-')[2])

In [78]:
df.Year.unique()

array(['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2007'], dtype=object)

In [79]:
df[['Year','Month','RainTomorrow']]

        Year Month RainTomorrow
0       2008    12           No
1       2008    12           No
2       2008    12           No
3       2008    12           No
4       2008    12           No
5       2008    12           No
6       2008    12           No
7       2008    12           No
8       2008    12          Yes
9       2008    12           No
10      2008    12          Yes
11      2008    12          Yes
12      2008    12          Yes
13      2008    12           No
14      2008    12           No
15      2008    12          Yes
16      2008    12          Yes
17      2008    12           No
18      2008    12           No
19      2008    12           No
20      2008    12           No
21      2008    12           No
22      2008    12           No
23      2008    12           No
24      2008    12           No
25      2008    12           No
26      2008    12           No
27      2008    12          Yes
28      2008    12           No
29      2008    12           No
...      ...   ...          ...
142163  2017    05           No
142164  2017    05           No
142165  2017    05           No
142166  2017    05           No
142167  2017    05           No
142168  2017    05           No
142169  2017    06           No
142170  2017    06           No
142171  2017    06           No
142172  2017    06           No
142173  2017    06           No
142174  2017    06           No
142175  2017    06           No
142176  2017    06           No
142177  2017    06           No
142178  2017    06           No
142179  2017    06           No
142180  2017    06           No
142181  2017    06           No
142182  2017    06           No
142183  2017    06           No
142184  2017    06           No
142185  2017    06           No
142186  2017    06           No
142187  2017    06           No
142188  2017    06           No
142189  2017    06           No
142190  2017    06           No
142191  2017    06           No
142192  2017    06           No

[142193 rows x 3 columns]

In [80]:
df[['Year','Month','RainTomorrow']].groupby(['Year','Month']).mode()

AttributeError: Cannot access callable attribute 'mode' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [81]:
import scipy.stats

In [82]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow',
       'Month', 'Year', 'Day'],
      dtype='object')

In [83]:
df[['Location','Year','Month','RainToday']]

       Location  Year Month RainToday
0        Albury  2008    12        No
1        Albury  2008    12        No
2        Albury  2008    12        No
3        Albury  2008    12        No
4        Albury  2008    12        No
5        Albury  2008    12        No
6        Albury  2008    12        No
7        Albury  2008    12        No
8        Albury  2008    12        No
9        Albury  2008    12       Yes
10       Albury  2008    12        No
11       Albury  2008    12       Yes
12       Albury  2008    12       Yes
13       Albury  2008    12       Yes
14       Albury  2008    12       NaN
15       Albury  2008    12        No
16       Albury  2008    12       Yes
17       Albury  2008    12       Yes
18       Albury  2008    12        No
19       Albury  2008    12        No
20       Albury  2008    12        No
21       Albury  2008    12        No
22       Albury  2008    12        No
23       Albury  2008    12        No
24       Albury  2008    12        No
25       Albury  2008    12        No
26       Albury  2008    12        No
27       Albury  2008    12        No
28       Albury  2008    12       Yes
29       Albury  2008    12        No
...         ...   ...   ...       ...
142163    Uluru  2017    05        No
142164    Uluru  2017    05        No
142165    Uluru  2017    05        No
142166    Uluru  2017    05        No
142167    Uluru  2017    05        No
142168    Uluru  2017    05        No
142169    Uluru  2017    06        No
142170    Uluru  2017    06        No
142171    Uluru  2017    06        No
142172    Uluru  2017    06        No
142173    Uluru  2017    06        No
142174    Uluru  2017    06        No
142175    Uluru  2017    06        No
142176    Uluru  2017    06        No
142177    Uluru  2017    06        No
142178    Uluru  2017    06        No
142179    Uluru  2017    06        No
142180    Uluru  2017    06        No
142181    Uluru  2017    06        No
142182    Uluru  2017    06        No
142183    Uluru  2017    06        No
142184    Uluru  2017    06        No
142185    Uluru  2017    06        No
142186    Uluru  2017    06        No
142187    Uluru  2017    06        No
142188    Uluru  2017    06        No
142189    Uluru  2017    06        No
142190    Uluru  2017    06        No
142191    Uluru  2017    06        No
142192    Uluru  2017    06        No

[142193 rows x 4 columns]

In [84]:
rain_today_mode = df[['Location','Year','Month','RainToday']][~df['RainToday'].isna()].groupby(['Location', 'Year','Month']).agg(lambda x: scipy.stats.mode(x)[0])['RainToday'].reset_index()

/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:248: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  "values. nan values will be ignored.", RuntimeWarning)

In [85]:
df[df['RainToday'].isna()]['RainToday']

14        NaN
282       NaN
433       NaN
434       NaN
439       NaN
447       NaN
449       NaN
457       NaN
603       NaN
974       NaN
1000      NaN
1360      NaN
1514      NaN
1667      NaN
1903      NaN
2011      NaN
2019      NaN
2889      NaN
2909      NaN
2916      NaN
3172      NaN
3181      NaN
3285      NaN
3306      NaN
3350      NaN
3376      NaN
3391      NaN
3395      NaN
3399      NaN
3406      NaN
         ...
139481    NaN
139484    NaN
140084    NaN
140135    NaN
140324    NaN
140475    NaN
140490    NaN
140496    NaN
140499    NaN
140531    NaN
140575    NaN
140701    NaN
141031    NaN
141040    NaN
141041    NaN
141042    NaN
141045    NaN
141047    NaN
141061    NaN
141072    NaN
141076    NaN
141506    NaN
141603    NaN
141651    NaN
141667    NaN
141678    NaN
141689    NaN
141693    NaN
141828    NaN
142070    NaN
Name: RainToday, Length: 1406, dtype: object

In [86]:
df2 = pd.merge(df, rain_today_mode, on=['Location','Year','Month'])

In [87]:
df2

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday_x,RainTomorrow,Month,Year,Day,RainToday_y
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,...,1007.7,1007.1,16.9,21.8,No,No,12,2008,01,No
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,...,1010.6,1007.8,17.2,24.3,No,No,12,2008,02,No
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,...,1007.6,1008.7,21.0,23.2,No,No,12,2008,03,No
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,...,1017.6,1012.8,18.1,26.5,No,No,12,2008,04,No
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,...,1010.8,1006.0,17.8,29.7,No,No,12,2008,05,No
5,2008-12-06,Albury,14.6,29.7,0.2,WNW,56.0,W,W,19.0,...,1009.2,1005.4,20.6,28.9,No,No,12,2008,06,No
6,2008-12-07,Albury,14.3,25.0,0.0,W,50.0,SW,W,20.0,...,1009.6,1008.2,18.1,24.6,No,No,12,2008,07,No
7,2008-12-08,Albury,7.7,26.7,0.0,W,35.0,SSE,W,6.0,...,1013.4,1010.1,16.3,25.5,No,No,12,2008,08,No
8,2008-12-09,Albury,9.7,31.9,0.0,NNW,80.0,SE,NW,7.0,...,1008.9,1003.6,18.3,30.2,No,Yes,12,2008,09,No
9,2008-12-10,Albury,13.1,30.1,1.4,W,28.0,S,SSE,15.0,...,1007.0,1005.7,20.1,28.2,Yes,No,12,2008,10,No
10,2008-12-11,Albury,13.4,30.4,0.0,N,30.0,SSE,ESE,17.0,...,1011.8,1008.7,20.4,28.8,No,Yes,12,2008,11,No
11,2008-12-12,Albury,15.9,21.7,2.2,NNE,31.0,NE,ENE,15.0,...,1010.5,1004.2,15.9,17.0,Yes,Yes,12,2008,12,No
12,2008-12-13,Albury,15.9,18.6,15.6,W,61.0,NNW,NNW,28.0,...,994.3,993.0,17.4,15.8,Yes,Yes,12,2008,13,No
13,2008-12-14,Albury,12.6,21.0,3.6,SW,44.0,W,SSW,24.0,...,1001.2,1001.8,15.8,19.8,Yes,No,12,2008,14,No
14,2008-12-16,Albury,9.8,27.7,NaN,WNW,50.0,NaN,WNW,NaN,...,1013.4,1010.3,17.3,26.2,NaN,No,12,2008,16,No
15,2008-12-17,Albury,14.1,20.9,0.0,ENE,22.0,SSW,E,11.0,...,1012.2,1010.4,17.2,18.1,No,Yes,12,2008,17,No
16,2008-12-18,Albury,13.5,22.9,16.8,W,63.0,N,WNW,6.0,...,1005.8,1002.2,18.0,21.5,Yes,Yes,12,2008,18,No
17,2008-12-19,Albury,11.2,22.5,10.6,SSE,43.0,WSW,SW,24.0,...,1009.4,1009.7,15.5,21.0,Yes,No,12,2008,19,No
18,2008-12-20,Albury,9.8,25.6,0.0,SSE,26.0,SE,NNW,17.0,...,1019.2,1017.1,15.8,23.2,No,No,12,2008,20,No
19,2008-12-21,Albury,11.5,29.3,0.0,S,24.0,SE,SE,9.0,...,1019.3,1014.8,19.1,27.3,No,No,12,2008,21,No
20,2008-12-22,Albury,17.1,33.0,0.0,NE,43.0,NE,N,17.0,...,1013.6,1008.1,24.5,31.6,No,No,12,2008,22,No
21,2008-12-23,Albury,20.5,31.8,0.0,WNW,41.0,W,W,19.0,...,1007.8,1005.7,23.8,30.8,No,No,12,2008,23,No
22,2008-12-24,Albury,15.3,30.9,0.0,N,33.0,ESE,NW,6.0,...,1011.0,1008.2,20.9,29.0,No,No,12,2008,24,No
23,2008-12-25,Albury,12.6,32.4,0.0,W,43.0,E,W,4.0,...,1012.9,1010.1,21.5,31.2,No,No,12,2008,25,No
24,2008-12-26,Albury,16.2,33.9,0.0,WSW,35.0,SE,WSW,9.0,...,1010.9,1007.6,23.2,33.0,No,No,12,2008,26,No
25,2008-12-27,Albury,16.9,33.0,0.0,WSW,57.0,NaN,W,0.0,...,1006.8,1003.6,26.6,31.2,No,No,12,2008,27,No
26,2008-12-28,Albury,20.1,32.7,0.0,WNW,48.0,N,WNW,13.0,...,1005.2,1001.7,24.6,32.1,No,No,12,2008,28,No
27,2008-12-29,Albury,19.7,27.2,0.0,WNW,46.0,NW,WSW,19.0,...,1004.8,1004.2,21.6,26.1,No,Yes,12,2008,29,No
28,2008-12-30,Albury,12.5,24.2,1.2,WNW,50.0,WSW,SW,11.0,...,1005.6,1003.4,12.5,18.2,Yes,No,12,2008,30,No
29,2008-12-31,Albury,12.0,24.4,0.8,W,39.0,WNW,WNW,17.0,...,1006.1,1005.1,16.9,22.7,No,No,12,2008,31,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142162,2017-05-26,Uluru,14.3,27.6,0.4,WNW,39.0,NaN,NW,0.0,...,1020.5,1016.1,16.1,27.2,No,No,05,2017,26,No
142163,2017-05-27,Uluru,9.3,28.0,0.0,W,28.0,SSW,WNW,6.0,...,1019.9,1016.9,16.6,27.3,No,No,05,2017,27,No
142164,2017-05-28,Uluru,8.0,24.6,0.0,E,33.0,SE,ESE,11.0,...,1021.7,1018.8,13.8,23.5,No,No,05,2017,28,No
142165,2017-05-29,Uluru,12.7,22.2,0.0,E,37.0,E,ESE,19.0,...,1024.3,1021.7,13.9,21.0,No,No,05,2017,29,No
142166,2017-05-30,Uluru,9.4,22.7,0.0,E,35.0,SE,E,13.0,...,1026.6,1023.6,11.8,22.3,No,No,05,2017,30,No
142167,2017-05-31,Uluru,5.4,20.5,0.0,E,46.0,E,E,20.0,...,1029.2,1025.3,11.1,20.2,No,No,05,2017,31,No
142168,2017-06-01,Uluru,5.6,19.4,0.0,E,43.0,E,ESE,22.0,...,1029.6,1027.1,9.7,18.3,No,No,06,2017,01,No
142169,2017-06-02,Uluru,1.5,19.2,0.0,E,37.0,ESE,ESE,17.0,...,1030.7,1026.7,6.8,17.6,No,No,06,2017,02,No
142170,2017-06-03,Uluru,3.8,19.8,0.0,ENE,39.0,ESE,E,19.0,...,1028.7,1024.1,8.6,18.9,No,No,06,2017,03,No
142171,2017-06-04,Uluru,4.5,18.8,0.0,E,31.0,ESE,E,13.0,...,1026.9,1022.4,9.5,18.6,No,No,06,2017,04,No
142172,2017-06-05,Uluru,4.9,20.7,0.0,E,37.0,ESE,ESE,17.0,...,1027.1,1023.9,10.3,19.8,No,No,06,2017,05,No
142173,2017-06-06,Uluru,1.2,20.8,0.0,E,43.0,ESE,E,13.0,...,1029.8,1025.9,7.9,19.9,No,No,06,2017,06,No
142174,2017-06-07,Uluru,0.5,21.7,0.0,E,43.0,ESE,ENE,13.0,...,1029.0,1025.0,9.5,20.5,No,No,06,2017,07,No
142175,2017-06-08,Uluru,4.0,20.0,0.0,SE,39.0,ESE,ESE,13.0,...,1030.2,1026.7,9.1,19.0,No,No,06,2017,08,No
142176,2017-06-09,Uluru,3.4,19.8,0.0,E,43.0,ESE,E,19.0,...,1031.8,1027.7,8.7,18.9,No,No,06,2017,09,No
142177,2017-06-10,Uluru,3.2,18.6,0.0,E,46.0,ESE,E,15.0,...,1031.0,1027.2,8.2,17.4,No,No,06,2017,10,No
142178,2017-06-11,Uluru,2.4,19.1,0.0,E,33.0,SE,E,17.0,...,1030.0,1026.2,8.0,18.8,No,No,06,2017,11,No
142179,2017-06-12,Uluru,5.1,19.7,0.0,E,46.0,ESE,E,13.0,...,1028.5,1025.8,8.5,19.2,No,No,06,2017,12,No
142180,2017-06-13,Uluru,2.5,21.2,0.0,ENE,35.0,ESE,E,17.0,...,1027.2,1023.0,10.3,20.3,No,No,06,2017,13,No
142181,2017-06-14,Uluru,2.3,21.4,0.0,SE,22.0,SE,SSE,11.0,...,1026.9,1022.8,8.9,20.3,No,No,06,2017,14,No
142182,2017-06-15,Uluru,2.6,22.5,0.0,S,19.0,S,E,9.0,...,1025.0,1021.4,8.8,22.1,No,No,06,2017,15,No
142183,2017-06-16,Uluru,5.2,24.3,0.0,E,24.0,SE,E,11.0,...,1023.8,1020.0,12.3,23.3,No,No,06,2017,16,No
142184,2017-06-17,Uluru,6.4,23.4,0.0,ESE,31.0,S,ESE,15.0,...,1025.8,1023.0,11.2,23.1,No,No,06,2017,17,No
142185,2017-06-18,Uluru,8.0,20.7,0.0,ESE,41.0,SE,E,19.0,...,1028.1,1024.3,11.6,20.0,No,No,06,2017,18,No
142186,2017-06-19,Uluru,7.4,20.6,0.0,E,35.0,ESE,E,15.0,...,1027.2,1023.3,11.0,20.3,No,No,06,2017,19,No
142187,2017-06-20,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,...,1024.7,1021.2,9.4,20.9,No,No,06,2017,20,No
142188,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,...,1024.6,1020.3,10.1,22.4,No,No,06,2017,21,No
142189,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,...,1023.5,1019.1,10.9,24.5,No,No,06,2017,22,No
142190,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,...,1021.0,1016.8,12.5,26.1,No,No,06,2017,23,No
142191,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,...,1019.4,1016.5,15.1,26.0,No,No,06,2017,24,No

In [88]:
df2[df2['RainToday_x'].isna()]['RainToday_y']

14         No
282        No
433        No
434        No
439        No
447        No
449        No
457        No
603        No
974        No
1000       No
1360       No
1514       No
1667       No
1903       No
2011       No
2019       No
2889       No
2909       No
2916       No
3172       No
3181       No
3285       No
3306       No
3350       No
3376       No
3391       No
3395       No
3399       No
3406       No
         ...
139480     No
139483     No
140083     No
140134    Yes
140323     No
140474     No
140489     No
140495     No
140498     No
140530    Yes
140574     No
140700     No
141030     No
141039     No
141040     No
141041     No
141044     No
141046     No
141060     No
141071     No
141075     No
141505     No
141602     No
141650     No
141666     No
141677     No
141688     No
141692     No
141827     No
142069     No
Name: RainToday_y, Length: 1405, dtype: object

In [89]:
df2.loc[df2['RainToday_x'].isna(), 'RainToday_x'] = df2[df2['RainToday_x'].isna()]['RainToday_y']

In [90]:
df2['RainToday_x'].unique()

array(['No', 'Yes'], dtype=object)

In [91]:
df3 = df2.drop('RainToday_y', axis=1)

In [92]:
# lets check if rainToday is always missing together with Rainfall ?

In [93]:
df.loc[df['RainToday'].isna(), 'Rainfall'].shape

(1406,)

In [94]:
# Yes all are missing together! \
#which means whenever we took the mode to be No we should insert 0 otherwise we will take the monthly average?

In [95]:
rainfall_mean = df[['Location','Year','Month','Rainfall']][~df['Rainfall'].isna()].groupby(['Location', 'Year','Month']).mean()['Rainfall'].reset_index()

In [96]:
rainfall_mean

      Location  Year Month  Rainfall
0     Adelaide  2008    07  3.361905
1     Adelaide  2008    08  3.838095
2     Adelaide  2008    09  0.615385
3     Adelaide  2008    10  0.292308
4     Adelaide  2008    11  0.475862
5     Adelaide  2008    12  1.303226
6     Adelaide  2009    01  0.038710
7     Adelaide  2009    02  0.028571
8     Adelaide  2009    03  0.690323
9     Adelaide  2009    04  2.453333
10    Adelaide  2009    05  2.032258
11    Adelaide  2009    06  1.733333
12    Adelaide  2009    07  3.516129
13    Adelaide  2009    08  1.862069
14    Adelaide  2009    09  2.274074
15    Adelaide  2009    10  0.593548
16    Adelaide  2009    11  1.406667
17    Adelaide  2009    12  0.587097
18    Adelaide  2010    01  0.296774
19    Adelaide  2010    02  0.200000
20    Adelaide  2010    03  0.612903
21    Adelaide  2010    04  1.653333
22    Adelaide  2010    05  1.958621
23    Adelaide  2010    06  2.350000
24    Adelaide  2010    07  2.135714
25    Adelaide  2010    08  4.107143
26    Adelaide  2010    09  2.406667
27    Adelaide  2010    10  0.941935
28    Adelaide  2010    11  0.773333
29    Adelaide  2010    12  2.806452
...        ...   ...   ...       ...
4737   Woomera  2015    01  2.864516
4738   Woomera  2015    02  0.000000
4739   Woomera  2015    03  0.000000
4740   Woomera  2015    04  0.793333
4741   Woomera  2015    05  0.006452
4742   Woomera  2015    06  0.273333
4743   Woomera  2015    07  0.096774
4744   Woomera  2015    08  0.470968
4745   Woomera  2015    09  0.126667
4746   Woomera  2015    10  0.032258
4747   Woomera  2015    11  0.380000
4748   Woomera  2015    12  0.122581
4749   Woomera  2016    01  0.012903
4750   Woomera  2016    02  0.524138
4751   Woomera  2016    03  0.774194
4752   Woomera  2016    04  0.033333
4753   Woomera  2016    05  0.945161
4754   Woomera  2016    06  1.890000
4755   Woomera  2016    07  0.222581
4756   Woomera  2016    08  0.890323
4757   Woomera  2016    09  1.500000
4758   Woomera  2016    10  0.335484
4759   Woomera  2016    11  0.016667
4760   Woomera  2016    12  0.505000
4761   Woomera  2017    01  1.664516
4762   Woomera  2017    02  0.000000
4763   Woomera  2017    03  0.000000
4764   Woomera  2017    04  1.356667
4765   Woomera  2017    05  0.341935
4766   Woomera  2017    06  0.008333

[4767 rows x 4 columns]

In [97]:
 df4 = pd.merge(df3, rainfall_mean, on=['Location','Year','Month'])

In [98]:
type(df4['RainToday_x'][1])

str

In [99]:
df4

,Date,Location,MinTemp,MaxTemp,Rainfall_x,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday_x,RainTomorrow,Month,Year,Day,Rainfall_y
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,...,1007.7,1007.1,16.9,21.8,No,No,12,2008,01,1.862069
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,...,1010.6,1007.8,17.2,24.3,No,No,12,2008,02,1.862069
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,...,1007.6,1008.7,21.0,23.2,No,No,12,2008,03,1.862069
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,...,1017.6,1012.8,18.1,26.5,No,No,12,2008,04,1.862069
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,...,1010.8,1006.0,17.8,29.7,No,No,12,2008,05,1.862069
5,2008-12-06,Albury,14.6,29.7,0.2,WNW,56.0,W,W,19.0,...,1009.2,1005.4,20.6,28.9,No,No,12,2008,06,1.862069
6,2008-12-07,Albury,14.3,25.0,0.0,W,50.0,SW,W,20.0,...,1009.6,1008.2,18.1,24.6,No,No,12,2008,07,1.862069
7,2008-12-08,Albury,7.7,26.7,0.0,W,35.0,SSE,W,6.0,...,1013.4,1010.1,16.3,25.5,No,No,12,2008,08,1.862069
8,2008-12-09,Albury,9.7,31.9,0.0,NNW,80.0,SE,NW,7.0,...,1008.9,1003.6,18.3,30.2,No,Yes,12,2008,09,1.862069
9,2008-12-10,Albury,13.1,30.1,1.4,W,28.0,S,SSE,15.0,...,1007.0,1005.7,20.1,28.2,Yes,No,12,2008,10,1.862069
10,2008-12-11,Albury,13.4,30.4,0.0,N,30.0,SSE,ESE,17.0,...,1011.8,1008.7,20.4,28.8,No,Yes,12,2008,11,1.862069
11,2008-12-12,Albury,15.9,21.7,2.2,NNE,31.0,NE,ENE,15.0,...,1010.5,1004.2,15.9,17.0,Yes,Yes,12,2008,12,1.862069
12,2008-12-13,Albury,15.9,18.6,15.6,W,61.0,NNW,NNW,28.0,...,994.3,993.0,17.4,15.8,Yes,Yes,12,2008,13,1.862069
13,2008-12-14,Albury,12.6,21.0,3.6,SW,44.0,W,SSW,24.0,...,1001.2,1001.8,15.8,19.8,Yes,No,12,2008,14,1.862069
14,2008-12-16,Albury,9.8,27.7,NaN,WNW,50.0,NaN,WNW,NaN,...,1013.4,1010.3,17.3,26.2,No,No,12,2008,16,1.862069
15,2008-12-17,Albury,14.1,20.9,0.0,ENE,22.0,SSW,E,11.0,...,1012.2,1010.4,17.2,18.1,No,Yes,12,2008,17,1.862069
16,2008-12-18,Albury,13.5,22.9,16.8,W,63.0,N,WNW,6.0,...,1005.8,1002.2,18.0,21.5,Yes,Yes,12,2008,18,1.862069
17,2008-12-19,Albury,11.2,22.5,10.6,SSE,43.0,WSW,SW,24.0,...,1009.4,1009.7,15.5,21.0,Yes,No,12,2008,19,1.862069
18,2008-12-20,Albury,9.8,25.6,0.0,SSE,26.0,SE,NNW,17.0,...,1019.2,1017.1,15.8,23.2,No,No,12,2008,20,1.862069
19,2008-12-21,Albury,11.5,29.3,0.0,S,24.0,SE,SE,9.0,...,1019.3,1014.8,19.1,27.3,No,No,12,2008,21,1.862069
20,2008-12-22,Albury,17.1,33.0,0.0,NE,43.0,NE,N,17.0,...,1013.6,1008.1,24.5,31.6,No,No,12,2008,22,1.862069
21,2008-12-23,Albury,20.5,31.8,0.0,WNW,41.0,W,W,19.0,...,1007.8,1005.7,23.8,30.8,No,No,12,2008,23,1.862069
22,2008-12-24,Albury,15.3,30.9,0.0,N,33.0,ESE,NW,6.0,...,1011.0,1008.2,20.9,29.0,No,No,12,2008,24,1.862069
23,2008-12-25,Albury,12.6,32.4,0.0,W,43.0,E,W,4.0,...,1012.9,1010.1,21.5,31.2,No,No,12,2008,25,1.862069
24,2008-12-26,Albury,16.2,33.9,0.0,WSW,35.0,SE,WSW,9.0,...,1010.9,1007.6,23.2,33.0,No,No,12,2008,26,1.862069
25,2008-12-27,Albury,16.9,33.0,0.0,WSW,57.0,NaN,W,0.0,...,1006.8,1003.6,26.6,31.2,No,No,12,2008,27,1.862069
26,2008-12-28,Albury,20.1,32.7,0.0,WNW,48.0,N,WNW,13.0,...,1005.2,1001.7,24.6,32.1,No,No,12,2008,28,1.862069
27,2008-12-29,Albury,19.7,27.2,0.0,WNW,46.0,NW,WSW,19.0,...,1004.8,1004.2,21.6,26.1,No,Yes,12,2008,29,1.862069
28,2008-12-30,Albury,12.5,24.2,1.2,WNW,50.0,WSW,SW,11.0,...,1005.6,1003.4,12.5,18.2,Yes,No,12,2008,30,1.862069
29,2008-12-31,Albury,12.0,24.4,0.8,W,39.0,WNW,WNW,17.0,...,1006.1,1005.1,16.9,22.7,No,No,12,2008,31,1.862069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142162,2017-05-26,Uluru,14.3,27.6,0.4,WNW,39.0,NaN,NW,0.0,...,1020.5,1016.1,16.1,27.2,No,No,05,2017,26,0.012903
142163,2017-05-27,Uluru,9.3,28.0,0.0,W,28.0,SSW,WNW,6.0,...,1019.9,1016.9,16.6,27.3,No,No,05,2017,27,0.012903
142164,2017-05-28,Uluru,8.0,24.6,0.0,E,33.0,SE,ESE,11.0,...,1021.7,1018.8,13.8,23.5,No,No,05,2017,28,0.012903
142165,2017-05-29,Uluru,12.7,22.2,0.0,E,37.0,E,ESE,19.0,...,1024.3,1021.7,13.9,21.0,No,No,05,2017,29,0.012903
142166,2017-05-30,Uluru,9.4,22.7,0.0,E,35.0,SE,E,13.0,...,1026.6,1023.6,11.8,22.3,No,No,05,2017,30,0.012903
142167,2017-05-31,Uluru,5.4,20.5,0.0,E,46.0,E,E,20.0,...,1029.2,1025.3,11.1,20.2,No,No,05,2017,31,0.012903
142168,2017-06-01,Uluru,5.6,19.4,0.0,E,43.0,E,ESE,22.0,...,1029.6,1027.1,9.7,18.3,No,No,06,2017,01,0.000000
142169,2017-06-02,Uluru,1.5,19.2,0.0,E,37.0,ESE,ESE,17.0,...,1030.7,1026.7,6.8,17.6,No,No,06,2017,02,0.000000
142170,2017-06-03,Uluru,3.8,19.8,0.0,ENE,39.0,ESE,E,19.0,...,1028.7,1024.1,8.6,18.9,No,No,06,2017,03,0.000000
142171,2017-06-04,Uluru,4.5,18.8,0.0,E,31.0,ESE,E,13.0,...,1026.9,1022.4,9.5,18.6,No,No,06,2017,04,0.000000
142172,2017-06-05,Uluru,4.9,20.7,0.0,E,37.0,ESE,ESE,17.0,...,1027.1,1023.9,10.3,19.8,No,No,06,2017,05,0.000000
142173,2017-06-06,Uluru,1.2,20.8,0.0,E,43.0,ESE,E,13.0,...,1029.8,1025.9,7.9,19.9,No,No,06,2017,06,0.000000
142174,2017-06-07,Uluru,0.5,21.7,0.0,E,43.0,ESE,ENE,13.0,...,1029.0,1025.0,9.5,20.5,No,No,06,2017,07,0.000000
142175,2017-06-08,Uluru,4.0,20.0,0.0,SE,39.0,ESE,ESE,13.0,...,1030.2,1026.7,9.1,19.0,No,No,06,2017,08,0.000000
142176,2017-06-09,Uluru,3.4,19.8,0.0,E,43.0,ESE,E,19.0,...,1031.8,1027.7,8.7,18.9,No,No,06,2017,09,0.000000
142177,2017-06-10,Uluru,3.2,18.6,0.0,E,46.0,ESE,E,15.0,...,1031.0,1027.2,8.2,17.4,No,No,06,2017,10,0.000000
142178,2017-06-11,Uluru,2.4,19.1,0.0,E,33.0,SE,E,17.0,...,1030.0,1026.2,8.0,18.8,No,No,06,2017,11,0.000000
142179,2017-06-12,Uluru,5.1,19.7,0.0,E,46.0,ESE,E,13.0,...,1028.5,1025.8,8.5,19.2,No,No,06,2017,12,0.000000
142180,2017-06-13,Uluru,2.5,21.2,0.0,ENE,35.0,ESE,E,17.0,...,1027.2,1023.0,10.3,20.3,No,No,06,2017,13,0.000000
142181,2017-06-14,Uluru,2.3,21.4,0.0,SE,22.0,SE,SSE,11.0,...,1026.9,1022.8,8.9,20.3,No,No,06,2017,14,0.000000
142182,2017-06-15,Uluru,2.6,22.5,0.0,S,19.0,S,E,9.0,...,1025.0,1021.4,8.8,22.1,No,No,06,2017,15,0.000000
142183,2017-06-16,Uluru,5.2,24.3,0.0,E,24.0,SE,E,11.0,...,1023.8,1020.0,12.3,23.3,No,No,06,2017,16,0.000000
142184,2017-06-17,Uluru,6.4,23.4,0.0,ESE,31.0,S,ESE,15.0,...,1025.8,1023.0,11.2,23.1,No,No,06,2017,17,0.000000
142185,2017-06-18,Uluru,8.0,20.7,0.0,ESE,41.0,SE,E,19.0,...,1028.1,1024.3,11.6,20.0,No,No,06,2017,18,0.000000
142186,2017-06-19,Uluru,7.4,20.6,0.0,E,35.0,ESE,E,15.0,...,1027.2,1023.3,11.0,20.3,No,No,06,2017,19,0.000000
142187,2017-06-20,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,...,1024.7,1021.2,9.4,20.9,No,No,06,2017,20,0.000000
142188,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,...,1024.6,1020.3,10.1,22.4,No,No,06,2017,21,0.000000
142189,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,...,1023.5,1019.1,10.9,24.5,No,No,06,2017,22,0.000000
142190,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,...,1021.0,1016.8,12.5,26.1,No,No,06,2017,23,0.000000
142191,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,...,1019.4,1016.5,15.1,26.0,No,No,06,2017,24,0.000000

In [100]:
df4.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall_x', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday_x', 'RainTomorrow',
       'Month', 'Year', 'Day', 'Rainfall_y'],
      dtype='object')

In [101]:
a = df4[['Rainfall_x', 'Rainfall_y', 'RainToday_x']].apply(lambda x: x['Rainfall_y'] if x['RainToday_x'] == 'Yes' else 0 , axis =1)

In [102]:
# assign 0 to rainfall whenever Rain today = No else assign mean

In [103]:
df4['Rainfall_x'] = df4[['Rainfall_x', 'Rainfall_y', 'RainToday_x']].apply(lambda x: x['Rainfall_y'] if x['RainToday_x'] == 'Yes' else 0 , axis =1)

In [104]:
# drop rainfall y

In [105]:
df5 = df4.drop('Rainfall_y', axis = 1)

In [106]:
# let's pick the mode also for the wind direction per location

In [107]:
wind_dir_9 = df[['Location','Year','Month','WindDir9am']][~df['WindDir9am'].isna()].groupby(['Location', 'Year','Month']).agg(lambda x: scipy.stats.mode(x)[0])['WindDir9am'].reset_index()

In [108]:
wind_dir_9

      Location  Year Month WindDir9am
0     Adelaide  2008    07          N
1     Adelaide  2008    08          N
2     Adelaide  2008    09          N
3     Adelaide  2008    10        NNE
4     Adelaide  2008    11          E
5     Adelaide  2008    12         NE
6     Adelaide  2009    01          N
7     Adelaide  2009    02          N
8     Adelaide  2009    03          S
9     Adelaide  2009    04         NE
10    Adelaide  2009    05          N
11    Adelaide  2009    06          N
12    Adelaide  2009    07          N
13    Adelaide  2009    08          N
14    Adelaide  2009    09          N
15    Adelaide  2009    10         SW
16    Adelaide  2009    11         NE
17    Adelaide  2009    12         SW
18    Adelaide  2010    01         SW
19    Adelaide  2010    02         SE
20    Adelaide  2010    03        ESE
21    Adelaide  2010    04        NNE
22    Adelaide  2010    05        NNE
23    Adelaide  2010    06         NE
24    Adelaide  2010    07         NE
25    Adelaide  2010    08          N
26    Adelaide  2010    09        WNW
27    Adelaide  2010    10        SSW
28    Adelaide  2010    11        WSW
29    Adelaide  2010    12        WSW
...        ...   ...   ...        ...
4721   Woomera  2015    01        SSE
4722   Woomera  2015    02        SSE
4723   Woomera  2015    03        SSE
4724   Woomera  2015    04         SE
4725   Woomera  2015    05        SSW
4726   Woomera  2015    06         SE
4727   Woomera  2015    07        ESE
4728   Woomera  2015    08          N
4729   Woomera  2015    09          E
4730   Woomera  2015    10         SE
4731   Woomera  2015    11          N
4732   Woomera  2015    12        ESE
4733   Woomera  2016    01         SE
4734   Woomera  2016    02        SSE
4735   Woomera  2016    03        ESE
4736   Woomera  2016    04        SSE
4737   Woomera  2016    05          N
4738   Woomera  2016    06         NW
4739   Woomera  2016    07          N
4740   Woomera  2016    08          N
4741   Woomera  2016    09        NNE
4742   Woomera  2016    10          N
4743   Woomera  2016    11         SE
4744   Woomera  2016    12        SSE
4745   Woomera  2017    01        SSE
4746   Woomera  2017    02        SSE
4747   Woomera  2017    03          S
4748   Woomera  2017    04        ESE
4749   Woomera  2017    05          E
4750   Woomera  2017    06          E

[4751 rows x 4 columns]

In [109]:
wind_dir_9.WindDir9am.unique()

array(['N', 'NNE', 'E', 'NE', 'S', 'SW', 'SE', 'ESE', 'WNW', 'SSW', 'WSW',
       'SSE', 'ENE', 'W', 'NNW', 'NW'], dtype=object)

In [110]:
wind_dir_3pm = df[['Location','Year','Month','WindDir3pm']][~df['WindDir3pm'].isna()].groupby(['Location', 'Year','Month']).agg(lambda x: scipy.stats.mode(x)[0])['WindDir3pm'].reset_index()

In [111]:
 df6 = pd.merge(df5, wind_dir_9, on=['Location','Year','Month'])

In [112]:
df6

,Date,Location,MinTemp,MaxTemp,Rainfall_x,WindGustDir,WindGustSpeed,WindDir9am_x,WindDir3pm,WindSpeed9am,...,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday_x,RainTomorrow,Month,Year,Day,WindDir9am_y
0,2008-12-01,Albury,13.4,22.9,0.000000,W,44.0,W,WNW,20.0,...,1007.7,1007.1,16.9,21.8,No,No,12,2008,01,SE
1,2008-12-02,Albury,7.4,25.1,0.000000,WNW,44.0,NNW,WSW,4.0,...,1010.6,1007.8,17.2,24.3,No,No,12,2008,02,SE
2,2008-12-03,Albury,12.9,25.7,0.000000,WSW,46.0,W,WSW,19.0,...,1007.6,1008.7,21.0,23.2,No,No,12,2008,03,SE
3,2008-12-04,Albury,9.2,28.0,0.000000,NE,24.0,SE,E,11.0,...,1017.6,1012.8,18.1,26.5,No,No,12,2008,04,SE
4,2008-12-05,Albury,17.5,32.3,0.000000,W,41.0,ENE,NW,7.0,...,1010.8,1006.0,17.8,29.7,No,No,12,2008,05,SE
5,2008-12-06,Albury,14.6,29.7,0.000000,WNW,56.0,W,W,19.0,...,1009.2,1005.4,20.6,28.9,No,No,12,2008,06,SE
6,2008-12-07,Albury,14.3,25.0,0.000000,W,50.0,SW,W,20.0,...,1009.6,1008.2,18.1,24.6,No,No,12,2008,07,SE
7,2008-12-08,Albury,7.7,26.7,0.000000,W,35.0,SSE,W,6.0,...,1013.4,1010.1,16.3,25.5,No,No,12,2008,08,SE
8,2008-12-09,Albury,9.7,31.9,0.000000,NNW,80.0,SE,NW,7.0,...,1008.9,1003.6,18.3,30.2,No,Yes,12,2008,09,SE
9,2008-12-10,Albury,13.1,30.1,1.862069,W,28.0,S,SSE,15.0,...,1007.0,1005.7,20.1,28.2,Yes,No,12,2008,10,SE
10,2008-12-11,Albury,13.4,30.4,0.000000,N,30.0,SSE,ESE,17.0,...,1011.8,1008.7,20.4,28.8,No,Yes,12,2008,11,SE
11,2008-12-12,Albury,15.9,21.7,1.862069,NNE,31.0,NE,ENE,15.0,...,1010.5,1004.2,15.9,17.0,Yes,Yes,12,2008,12,SE
12,2008-12-13,Albury,15.9,18.6,1.862069,W,61.0,NNW,NNW,28.0,...,994.3,993.0,17.4,15.8,Yes,Yes,12,2008,13,SE
13,2008-12-14,Albury,12.6,21.0,1.862069,SW,44.0,W,SSW,24.0,...,1001.2,1001.8,15.8,19.8,Yes,No,12,2008,14,SE
14,2008-12-16,Albury,9.8,27.7,0.000000,WNW,50.0,NaN,WNW,NaN,...,1013.4,1010.3,17.3,26.2,No,No,12,2008,16,SE
15,2008-12-17,Albury,14.1,20.9,0.000000,ENE,22.0,SSW,E,11.0,...,1012.2,1010.4,17.2,18.1,No,Yes,12,2008,17,SE
16,2008-12-18,Albury,13.5,22.9,1.862069,W,63.0,N,WNW,6.0,...,1005.8,1002.2,18.0,21.5,Yes,Yes,12,2008,18,SE
17,2008-12-19,Albury,11.2,22.5,1.862069,SSE,43.0,WSW,SW,24.0,...,1009.4,1009.7,15.5,21.0,Yes,No,12,2008,19,SE
18,2008-12-20,Albury,9.8,25.6,0.000000,SSE,26.0,SE,NNW,17.0,...,1019.2,1017.1,15.8,23.2,No,No,12,2008,20,SE
19,2008-12-21,Albury,11.5,29.3,0.000000,S,24.0,SE,SE,9.0,...,1019.3,1014.8,19.1,27.3,No,No,12,2008,21,SE
20,2008-12-22,Albury,17.1,33.0,0.000000,NE,43.0,NE,N,17.0,...,1013.6,1008.1,24.5,31.6,No,No,12,2008,22,SE
21,2008-12-23,Albury,20.5,31.8,0.000000,WNW,41.0,W,W,19.0,...,1007.8,1005.7,23.8,30.8,No,No,12,2008,23,SE
22,2008-12-24,Albury,15.3,30.9,0.000000,N,33.0,ESE,NW,6.0,...,1011.0,1008.2,20.9,29.0,No,No,12,2008,24,SE
23,2008-12-25,Albury,12.6,32.4,0.000000,W,43.0,E,W,4.0,...,1012.9,1010.1,21.5,31.2,No,No,12,2008,25,SE
24,2008-12-26,Albury,16.2,33.9,0.000000,WSW,35.0,SE,WSW,9.0,...,1010.9,1007.6,23.2,33.0,No,No,12,2008,26,SE
25,2008-12-27,Albury,16.9,33.0,0.000000,WSW,57.0,NaN,W,0.0,...,1006.8,1003.6,26.6,31.2,No,No,12,2008,27,SE
26,2008-12-28,Albury,20.1,32.7,0.000000,WNW,48.0,N,WNW,13.0,...,1005.2,1001.7,24.6,32.1,No,No,12,2008,28,SE
27,2008-12-29,Albury,19.7,27.2,0.000000,WNW,46.0,NW,WSW,19.0,...,1004.8,1004.2,21.6,26.1,No,Yes,12,2008,29,SE
28,2008-12-30,Albury,12.5,24.2,1.862069,WNW,50.0,WSW,SW,11.0,...,1005.6,1003.4,12.5,18.2,Yes,No,12,2008,30,SE
29,2008-12-31,Albury,12.0,24.4,0.000000,W,39.0,WNW,WNW,17.0,...,1006.1,1005.1,16.9,22.7,No,No,12,2008,31,SE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141690,2017-05-26,Uluru,14.3,27.6,0.000000,WNW,39.0,NaN,NW,0.0,...,1020.5,1016.1,16.1,27.2,No,No,05,2017,26,ESE
141691,2017-05-27,Uluru,9.3,28.0,0.000000,W,28.0,SSW,WNW,6.0,...,1019.9,1016.9,16.6,27.3,No,No,05,2017,27,ESE
141692,2017-05-28,Uluru,8.0,24.6,0.000000,E,33.0,SE,ESE,11.0,...,1021.7,1018.8,13.8,23.5,No,No,05,2017,28,ESE
141693,2017-05-29,Uluru,12.7,22.2,0.000000,E,37.0,E,ESE,19.0,...,1024.3,1021.7,13.9,21.0,No,No,05,2017,29,ESE
141694,2017-05-30,Uluru,9.4,22.7,0.000000,E,35.0,SE,E,13.0,...,1026.6,1023.6,11.8,22.3,No,No,05,2017,30,ESE
141695,2017-05-31,Uluru,5.4,20.5,0.000000,E,46.0,E,E,20.0,...,1029.2,1025.3,11.1,20.2,No,No,05,2017,31,ESE
141696,2017-06-01,Uluru,5.6,19.4,0.000000,E,43.0,E,ESE,22.0,...,1029.6,1027.1,9.7,18.3,No,No,06,2017,01,ESE
141697,2017-06-02,Uluru,1.5,19.2,0.000000,E,37.0,ESE,ESE,17.0,...,1030.7,1026.7,6.8,17.6,No,No,06,2017,02,ESE
141698,2017-06-03,Uluru,3.8,19.8,0.000000,ENE,39.0,ESE,E,19.0,...,1028.7,1024.1,8.6,18.9,No,No,06,2017,03,ESE
141699,2017-06-04,Uluru,4.5,18.8,0.000000,E,31.0,ESE,E,13.0,...,1026.9,1022.4,9.5,18.6,No,No,06,2017,04,ESE
141700,2017-06-05,Uluru,4.9,20.7,0.000000,E,37.0,ESE,ESE,17.0,...,1027.1,1023.9,10.3,19.8,No,No,06,2017,05,ESE
141701,2017-06-06,Uluru,1.2,20.8,0.000000,E,43.0,ESE,E,13.0,...,1029.8,1025.9,7.9,19.9,No,No,06,2017,06,ESE
141702,2017-06-07,Uluru,0.5,21.7,0.000000,E,43.0,ESE,ENE,13.0,...,1029.0,1025.0,9.5,20.5,No,No,06,2017,07,ESE
141703,2017-06-08,Uluru,4.0,20.0,0.000000,SE,39.0,ESE,ESE,13.0,...,1030.2,1026.7,9.1,19.0,No,No,06,2017,08,ESE
141704,2017-06-09,Uluru,3.4,19.8,0.000000,E,43.0,ESE,E,19.0,...,1031.8,1027.7,8.7,18.9,No,No,06,2017,09,ESE
141705,2017-06-10,Uluru,3.2,18.6,0.000000,E,46.0,ESE,E,15.0,...,1031.0,1027.2,8.2,17.4,No,No,06,2017,10,ESE
141706,2017-06-11,Uluru,2.4,19.1,0.000000,E,33.0,SE,E,17.0,...,1030.0,1026.2,8.0,18.8,No,No,06,2017,11,ESE
141707,2017-06-12,Uluru,5.1,19.7,0.000000,E,46.0,ESE,E,13.0,...,1028.5,1025.8,8.5,19.2,No,No,06,2017,12,ESE
141708,2017-06-13,Uluru,2.5,21.2,0.000000,ENE,35.0,ESE,E,17.0,...,1027.2,1023.0,10.3,20.3,No,No,06,2017,13,ESE
141709,2017-06-14,Uluru,2.3,21.4,0.000000,SE,22.0,SE,SSE,11.0,...,1026.9,1022.8,8.9,20.3,No,No,06,2017,14,ESE
141710,2017-06-15,Uluru,2.6,22.5,0.000000,S,19.0,S,E,9.0,...,1025.0,1021.4,8.8,22.1,No,No,06,2017,15,ESE
141711,2017-06-16,Uluru,5.2,24.3,0.000000,E,24.0,SE,E,11.0,...,1023.8,1020.0,12.3,23.3,No,No,06,2017,16,ESE
141712,2017-06-17,Uluru,6.4,23.4,0.000000,ESE,31.0,S,ESE,15.0,...,1025.8,1023.0,11.2,23.1,No,No,06,2017,17,ESE
141713,2017-06-18,Uluru,8.0,20.7,0.000000,ESE,41.0,SE,E,19.0,...,1028.1,1024.3,11.6,20.0,No,No,06,2017,18,ESE
141714,2017-06-19,Uluru,7.4,20.6,0.000000,E,35.0,ESE,E,15.0,...,1027.2,1023.3,11.0,20.3,No,No,06,2017,19,ESE
141715,2017-06-20,Uluru,3.5,21.8,0.000000,E,31.0,ESE,E,15.0,...,1024.7,1021.2,9.4,20.9,No,No,06,2017,20,ESE
141716,2017-06-21,Uluru,2.8,23.4,0.000000,E,31.0,SE,ENE,13.0,...,1024.6,1020.3,10.1,22.4,No,No,06,2017,21,ESE
141717,2017-06-22,Uluru,3.6,25.3,0.000000,NNW,22.0,SE,N,13.0,...,1023.5,1019.1,10.9,24.5,No,No,06,2017,22,ESE
141718,2017-06-23,Uluru,5.4,26.9,0.000000,N,37.0,SE,WNW,9.0,...,1021.0,1016.8,12.5,26.1,No,No,06,2017,23,ESE
141719,2017-06-24,Uluru,7.8,27.0,0.000000,SE,28.0,SSE,N,13.0,...,1019.4,1016.5,15.1,26.0,No,No,06,2017,24,ESE

In [113]:
df6.loc[df6['WindDir9am_x'].isna(), 'WindDir9am_x']

14        NaN
25        NaN
64        NaN
85        NaN
87        NaN
94        NaN
101       NaN
109       NaN
111       NaN
114       NaN
115       NaN
117       NaN
118       NaN
120       NaN
121       NaN
123       NaN
131       NaN
133       NaN
135       NaN
141       NaN
142       NaN
149       NaN
150       NaN
154       NaN
157       NaN
158       NaN
159       NaN
167       NaN
168       NaN
170       NaN
         ...
141206    NaN
141207    NaN
141208    NaN
141209    NaN
141210    NaN
141211    NaN
141212    NaN
141213    NaN
141214    NaN
141215    NaN
141264    NaN
141327    NaN
141344    NaN
141345    NaN
141346    NaN
141347    NaN
141348    NaN
141349    NaN
141350    NaN
141351    NaN
141352    NaN
141353    NaN
141354    NaN
141372    NaN
141382    NaN
141392    NaN
141431    NaN
141585    NaN
141683    NaN
141690    NaN
Name: WindDir9am_x, Length: 9541, dtype: object

In [114]:
df6.loc[df6['WindDir9am_x'].isna(), 'WindDir9am_x'] = df6[df6['WindDir9am_x'].isna()]['WindDir9am_y']

In [115]:
 df7 = pd.merge(df6, wind_dir_3pm, on=['Location','Year','Month'])

In [116]:
df7.loc[df7['WindDir3pm_x'].isna(), 'WindDir3pm_x'] = df7[df7['WindDir3pm_x'].isna()]['WindDir3pm_y']

In [117]:
# let's check there are no more winDir nan

In [118]:
list(df7.columns[(df7.isna().sum() > 0)])

['MinTemp',
 'MaxTemp',
 'WindGustDir',
 'WindGustSpeed',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Temp9am',
 'Temp3pm']

In [119]:
df7[df7.isna().sum() > 0]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match

In [ ]:
# let's drop the y columnms of WindDir

In [ ]:
df8 = df7.drop(['WindDir3pm_y', 'WindDir9am_y'], axis=1)

In [ ]:
df8['WindGustDir'].unique()

In [ ]:
WindGustDir = df[['Location','Year','Month','WindGustDir']][~df['WindGustDir'].isna()].groupby(['Location', 'Year','Month']).agg(lambda x: scipy.stats.mode(x)[0])['WindGustDir'].reset_index()

In [ ]:
 df9 = pd.merge(df8, WindGustDir, on=['Location','Year','Month'])

In [ ]:
df9.loc[df9['WindGustDir_x'].isna(), 'WindGustDir_x'] = df9[df9['WindGustDir_x'].isna()]['WindGustDir_y']

In [ ]:
df9

In [ ]:
# lets look at the distribution of columns with missing values per location per month

In [ ]:
dist_outlook = df9.groupby(['Location', 'Month', 'Day']).mean().reset_index()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
for i in range(1, 13):
    if i < 10:
        month = '0' + str(i)
    else: 
        month = str(i)
    plt.hist(dist_outlook.loc[(dist_outlook['Location']=='Adelaide') & (dist_outlook['Month'] == month) , 'MinTemp'])
    plt.show()

In [ ]:
import seaborn as sns
corr_plots = sns.PairGrid(df9)
corr_plots.map(plt.scatter);

In [ ]:
# let's choose the median for all other values to avoid surprises from outliers

In [ ]:
for column in list(df9.columns[(df9.isna().sum() > 0)]):
    median = df[['Location','Year','Month',column]][~df[column].isna()].groupby(['Location', 'Year','Month']).median().reset_index()
    df9 = pd.merge(df9, median, on=['Location','Year','Month'])
    df9.loc[df9[column + '_x'].isna(), column + '_x'] = df9[df9[column + '_x'].isna()][column + '_y']

In [ ]:
# Do we still have missing values?

In [ ]:
sum(df9.isna().sum())

In [ ]:
# Yayy No missing values

In [ ]:
# let's remove any column ending with _y

In [120]:
print (~df9.columns.str.endswith('_y'))

NameError: name 'df9' is not defined

In [121]:
df9 = df9.loc[:,~df9.columns.str.endswith('_y')]

NameError: name 'df9' is not defined

In [122]:
df9.columns

NameError: name 'df9' is not defined

In [123]:
# Next step would be to get rid of Date column since we have the year, Month, Day columns (we need to turn them to numeric values - they don't need to be categorical under a tree model)
# and then turn all categorical to dummies

In [124]:
pd.get_dummies(df8[['Location', 'WindDir9am_x']])

NameError: name 'df8' is not defined

In [125]:
dummies =  pd.get_dummies(df9[['Location', 'WindGustDir_x', 'WindDir9am_x', 'WindDir3pm_x', 'RainToday_x']], ['Location', 'WindGustDir_x', 'WindDir9am_x', 'WindDir3pm_x', 'RainToday_x'])

NameError: name 'df9' is not defined

In [126]:
df9 = df9.drop(['Location', 'WindGustDir_x', 'WindDir9am_x', 'WindDir3pm_x', 'RainToday_x'], axis =1)

NameError: name 'df9' is not defined

In [127]:
df9 = pd.concat([df9, dummies], axis=1)

NameError: name 'df9' is not defined

In [249]:
df9['Year'] = df9['Year'].astype(int)

In [262]:
df9 = df9.drop('Date', axis =1)

In [263]:
index_split = df9['Year'] > 2014

In [264]:
# let's split the data according to year

In [252]:
index_split

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
123466     True
123467     True
123468     True
123469     True
123470     True
123471     True
123472     True
123473     True
123474     True
123475     True
123476     True
123477     True
123478     True
123479     True
123480     True
123481     True
123482     True
123483     True
123484     True
123485     True
123486     True
123487     True
123488     True
123489     True
123490     True
123491     True
123492     True
123493     True
123494     True
123495     True
Name: Year, Length: 123496, dtype: bool

In [282]:
# let's turn the RainTomorrow column to numeric 0/1

In [271]:
df9['RainTomorrow'] = df9['RainTomorrow'].apply(lambda x: 1 if x == 'Yes' else 0)

In [272]:
tr_x, tr_y, te_x, te_y = df9.loc[index_split, df9.columns != 'RainTomorrow'], df9.loc[index_split, 'RainTomorrow'], df9.loc[~index_split, df9.columns != 'RainTomorrow'], df9.loc[~index_split,'RainTomorrow']

In [273]:
from sklearn import tree, ensemble

In [274]:
clf = tree.DecisionTreeClassifier()

In [275]:
clf = clf.fit(tr_x, tr_y)

In [276]:
y_hat = clf.predict(te_x)

In [281]:
np.sum(y_hat)/ len(y_hat)

0.23371037854416732

In [ ]:
# let's calculate the misclassification error

In [289]:
np.where((y_hat == te_y) == False)[0].shape[0]/ te_y.shape[0]

0.21840949185374797

In [290]:
clf = ensemble.RandomForestClassifier()

In [291]:
clf = clf.fit(tr_x, tr_y)

/Users/onivron/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [292]:
y_hat = clf.predict(te_x)

In [293]:
np.where((y_hat == te_y) == False)[0].shape[0]/ te_y.shape[0]

0.15890091897563619